// Port of keiyoushi/extensions-source src/en/mangaka/MangaKa.kt (generated by tools/generate.ts)
import { ChapterMode, Madara } from "../../../themes/madara/index.ts";

export default class MangaKa extends Madara {
  override chapterMode = ChapterMode.AdminAjax;
}
