// Port of keiyoushi/extensions-source src/en/mangareadorg/MangaReadOrg.kt (generated by tools/generate.ts)
import { DateTimeFormatter, Locale } from "../../../sdk/index.ts";
import { ChapterMode, Madara } from "../../../themes/madara/index.ts";

export default class MangaReadOrg extends Madara {
  override chapterDateFormat = DateTimeFormatter.ofPattern("dd.MM.yyy", Locale.US);

  override chapterMode = ChapterMode.MangaAjax;
}
