// Port of keiyoushi/extensions-source src/en/gakamangas/GakaMangas.kt (generated by tools/generate.ts)
import { ChapterMode, Madara } from "../../../themes/madara/index.ts";

export default class GakaMangas extends Madara {
  override filterNonMangaItems = false;

  override chapterMode = ChapterMode.MangaAjax;
}
