// Port of keiyoushi/extensions-source src/en/mangatrend/MangaTrend.kt (generated by tools/generate.ts)
import { MangaThemesia } from "../../../themes/mangathemesia/index.ts";

export default class MangaTrend extends MangaThemesia {}
