// Generated by tools/messages.ts from upstream src/all/manhuarm/assets/i18n (messages_manhuarm_*). Do not edit.
import type { Messages } from "../../../sdk/i18n.ts";

export const messages: Messages = {
  "en": {
    "font_name_title": "Font name",
    "font_name_summary": "Customize dialogues by choosing your preferred font. To apply the change to chapters that have already been read, you will need to clear the chapter cache in \"More > Data and storage > Clear chapter cache\". Font changes will not affect downloaded chapters",
    "font_name_message": "Font name changed to %s",
    "font_name_device_title": "Device",
    "font_size_title": "Font size",
    "font_size_summary": "Font changes will not be applied to downloaded or cached chapters. The font size will be adjusted according to the size of the dialog box.",
    "font_size_message": "Font size changed to %s",
    "default_font_size": "Default",
    "default_font_name": "Default",
    "disable_word_break_title": "Disable word break",
    "disable_word_break_summary": "This feature prevents words from being automatically broken in the middle of a line.",
    "disable_translator_title": "Disable translator",
    "disable_translator_summary": "Disable auto translation and enable source translation. This does not mean that a translation is available. Make sure a translation is available before enabling this option.",
    "translate_dialog_box_title": "Translator",
    "translate_dialog_box_summary": "Engine used to translate dialog boxes",
    "translate_dialog_box_toast": "The translator has been changed to",
    "dialog_box_scale_title": "Dialog box scale",
    "dialog_box_scale_default": "Default",
    "dialog_box_scale_summary": "Customize the size of the dialog box. This can be useful if you want larger fonts. Setting a value greater than 1.0x will cause the text to overflow the expected dialog box",
    "dialog_box_scale_message": "Dialog box scale changed to %s",
    "custom_user_agent_title": "Custom User-Agent",
    "custom_user_agent_message": "Set a custom User-Agent for requests. Leave blank to use the default.",
    "translate_synopsis_title": "Translate synopsis",
    "translate_synopsis_summary": "Automatically translate the manga description to your language. This may cause a slight delay when opening the manga details."
  },
  "es": {
    "font_size_title": "Tamaño de letra"
  },
  "fr": {
    "font_size_title": "Taille de la police"
  },
  "id": {
    "font_name_title": "Nama font",
    "font_name_summary": "Sesuaikan dialog dengan memilih font pilihan Anda. Untuk menerapkan perubahan ke bab yang sudah dibaca, Anda perlu menghapus cache bab di \"Lainnya > Data dan penyimpanan > Hapus cache bab\". Perubahan font tidak akan memengaruhi bab yang diunduh",
    "font_name_message": "Nama font diubah menjadi %s",
    "font_name_device_title": "Perangkat",
    "font_size_title": "Ukuran font",
    "font_size_summary": "Perubahan font tidak akan diterapkan pada bab yang diunduh atau disimpan di cache. Ukuran font akan disesuaikan menurut ukuran kotak dialog.",
    "font_size_message": "Ukuran font diubah menjadi %s",
    "disable_word_break_title": "Nonaktifkan pemutusan kata",
    "disable_word_break_summary": "Fitur ini mencegah kata-kata terputus secara otomatis di tengah baris.",
    "disable_translator_title": "Nonaktifkan penerjemah",
    "disable_translator_summary": "Nonaktifkan terjemahan otomatis dan aktifkan terjemahan sumber. Ini tidak berarti bahwa terjemahan tersedia. Pastikan terjemahan tersedia sebelum mengaktifkan opsi ini.",
    "translate_dialog_box_title": "Penerjemah",
    "translate_dialog_box_summary": "Mesin yang digunakan untuk menerjemahkan kotak dialog",
    "translate_dialog_box_toast": "Penerjemah telah diubah menjadi",
    "dialog_box_scale_title": "Skala kotak dialog",
    "dialog_box_scale_summary": "Sesuaikan ukuran kotak dialog. Ini berguna jika Anda menginginkan font yang lebih besar. Menyetel nilai lebih besar dari 1.0x akan menyebabkan teks meluap dari kotak dialog yang diharapkan",
    "dialog_box_scale_message": "Skala kotak dialog diubah menjadi %s",
    "custom_user_agent_title": "User-Agent Kustom",
    "custom_user_agent_message": "Atur User-Agent kustom untuk permintaan. Biarkan kosong untuk menggunakan default.",
    "translate_synopsis_title": "Terjemahkan sinopsis",
    "translate_synopsis_summary": "Terjemahkan deskripsi manga ke bahasa Anda secara otomatis. Ini mungkin menyebabkan sedikit penundaan saat membuka detail manga."
  },
  "it": {
    "font_size_title": "Dimensione del carattere"
  },
  "pt-BR": {
    "font_name_title": "Fonte",
    "font_name_summary": "Personalize os diálogos escolhendo a fonte de sua preferência. Para aplicar a alteração em capitulos lidos será necessário limpar o cache de capitulos em \"Mais > Dados e armazenamento > Limpar cache de capítulos\". As alterações de fonte não serão aplicadas aos capítulos baixados.",
    "font_name_message": "Fonte alterada para %s",
    "font_name_device_title": "Dispositivo",
    "font_size_title": "Tamanho da fonte",
    "font_size_summary": "As alterações de fonte não serão aplicadas aos capítulos baixados ou armazenados em cache. O tamanho da fonte será ajustado de acordo com o tamanho da caixa de diálogo.",
    "font_size_message": "Tamanho da fonte foi alterada para %s",
    "default_font_size": "Padrão",
    "default_font_name": "Padrão",
    "disable_word_break_title": "Desativar quebra de palavras",
    "disable_word_break_summary": "Esse recurso impede que palavras sejam quebradas automaticamente no meio da linha.",
    "disable_translator_title": "Desativar tradutor",
    "disable_translator_summary": "Desativar tradução automática e ativar tradução da fonte. Isso não significa que há uma tradução disponivel. Certifique-se de que exista uma tradução antes de ativar esta opção no site.",
    "translate_dialog_box_title": "Tradutor",
    "translate_dialog_box_summary": "Motor utilizado para traduzir caixas de diálogo",
    "translate_dialog_box_toast": "O tradutor foi alterado para",
    "dialog_box_scale_title": "Escala da caixa de diálogo",
    "dialog_box_scale_default": "Padrão",
    "dialog_box_scale_summary": "Personalize o tamanho da caixa de diálogo. Isso pode ser útil se você desejar fontes maiores. Definir um valor maior que 1,0x fará com que o texto ultrapasse os limites da caixa de diálogo esperada",
    "dialog_box_scale_message": "A escala da caixa de diálogo foi alterada para %s",
    "custom_user_agent_title": "User-Agent personalizado",
    "custom_user_agent_message": "Defina um User-Agent personalizado para solicitações. Deixe em branco para usar o padrão.."
  }
};
