// Generated by tools/messages.ts from upstream pam/assets/i18n. Do not edit.
import type { Messages } from "../../sdk/i18n.ts";

export const messages: Messages = {
  "en": {
    "release_year": "Release Year",
    "alternative_names": "Alternative Names",
    "pref_hide_premium_title": "Hide Premium chapters"
  },
  "fr": {
    "release_year": "Sortie",
    "alternative_names": "Noms alternatifs",
    "pref_hide_premium_title": "Masquer les chapitres Premium"
  }
};
