// Port of keiyoushi/extensions-source src/en/manhuaplus/ManhuaPlus.kt (generated by tools/generate.ts)
import { Madara } from "../../../themes/madara/index.ts";

export default class ManhuaPlus extends Madara {
  override filterNonMangaItems = false;

  override pageListParseSelector = ".read-container img";
}
