// Port of keiyoushi/extensions-source src/en/hentaixcomic/HentaiXComic.kt (generated by tools/generate.ts)
import { DateTimeFormatter, Locale } from "../../../sdk/index.ts";
import { ChapterMode, Madara } from "../../../themes/madara/index.ts";

export default class HentaiXComic extends Madara {
  override chapterDateFormat = DateTimeFormatter.ofPattern("MMM d, uuuu", Locale.US);

  override chapterMode = ChapterMode.MangaAjax;
}
