// Port of keiyoushi/extensions-source src/en/mangasushi/Mangasushi.kt (generated by tools/generate.ts)
import { ChapterMode, Madara } from "../../../themes/madara/index.ts";

export default class Mangasushi extends Madara {
  override chapterMode = ChapterMode.MangaAjax;
}
