// Port of keiyoushi/extensions-source src/en/rizzcomicunoriginal/RizzComicUnoriginal.kt (generated by tools/generate.ts)
import { MangaThemesia } from "../../../themes/mangathemesia/index.ts";

export default class RizzComicUnoriginal extends MangaThemesia {}
