// Port of keiyoushi/extensions-source src/en/lhtranslation/LHTranslation.kt (generated by tools/generate.ts)
import { ChapterMode, Madara } from "../../../themes/madara/index.ts";

export default class LHTranslation extends Madara {
  override chapterMode = ChapterMode.MangaAjax;
}
