// Port of keiyoushi/extensions-source src/en/kingofshojo/KingofShojo.kt (generated by tools/generate.ts)
import { MangaThemesia } from "../../../themes/mangathemesia/index.ts";

export default class KingofShojo extends MangaThemesia {}
