// Port of keiyoushi/extensions-source src/en/likemangain/MangaYY.kt (generated by tools/generate.ts)
import { DateTimeFormatter, Locale } from "../../../sdk/index.ts";
import { ChapterMode, Madara } from "../../../themes/madara/index.ts";

export default class MangaYY extends Madara {
  override chapterDateFormat = DateTimeFormatter.ofPattern("dd MMMM, yyyy", Locale.US);

  override chapterMode = ChapterMode.MangaAjax;
}
