// Port of keiyoushi/extensions-source src/all/kodokustudio/KodokuStudio.kt (generated by tools/generate.ts)
import { ChapterMode, Madara } from "../../../themes/madara/index.ts";

export default class KodokuStudio extends Madara {
  override chapterMode = ChapterMode.MangaAjax;

  override mangaSubString = "manhua";
}
