// Port of keiyoushi/extensions-source src/id/izanamiscans/IzanamiScans.kt (generated by tools/generate.ts)
import { ClientBuilder } from "../../../sdk/index.ts";
import { MangaThemesia } from "../../../themes/mangathemesia/index.ts";

export default class IzanamiScans extends MangaThemesia {
  protected override configureClient(b: ClientBuilder) {
    b.rateLimit(3, 1000);
    return b;
  }

  override seriesAuthorSelector = ".fmed b:contains(Penulis) + span";
}
