// Port of keiyoushi/extensions-source src/en/topmanhua/TopManhua.kt (generated by tools/generate.ts)
import { ClientBuilder, DateTimeFormatter, Locale } from "../../../sdk/index.ts";
import { ChapterMode, Madara } from "../../../themes/madara/index.ts";

export default class TopManhua extends Madara {
  override chapterMode = ChapterMode.MangaAjaxPaginated;

  override chapterDateFormat = DateTimeFormatter.ofPattern("MM/dd/yy", Locale.US);

  protected override configureClient(b: ClientBuilder) {
    b.rateLimit(2, 1000, (it: URL) => !it.pathname.startsWith("/wp-content/uploads/"));
    return b;
  }

  override filterNonMangaItems = false;

  override mangaSubString = "series";
}
