// Port of keiyoushi/extensions-source src/en/mangadia/MangaDia.kt (generated by tools/generate.ts)
import { DateTimeFormatter, Locale } from "../../../sdk/index.ts";
import { ChapterMode, Madara } from "../../../themes/madara/index.ts";

export default class MangaDia extends Madara {
  override chapterDateFormat = DateTimeFormatter.ofPattern("d MMMM yyyy", Locale.forLanguageTag("tr"));

  override chapterMode = ChapterMode.MangaAjax;
}
