// Port of keiyoushi/extensions-source src/en/mangaowlio/MangaOwlIo.kt (generated by tools/generate.ts)
import { ChapterMode, Madara } from "../../../themes/madara/index.ts";

export default class MangaOwlIo extends Madara {
  override mangaSubString = "read-1";

  override chapterMode = ChapterMode.MangaAjax;
}
