// Port of keiyoushi/extensions-source src/en/mangafree/Mangafree.kt (generated by tools/generate.ts)
import { ChapterMode, Madara } from "../../../themes/madara/index.ts";

export default class Mangafree extends Madara {
  override chapterMode = ChapterMode.MangaAjax;
}
