// Port of keiyoushi/extensions-source src/en/decadencescans/DecadenceScans.kt (generated by tools/generate.ts)
import { ChapterMode, Madara } from "../../../themes/madara/index.ts";

export default class DecadenceScans extends Madara {
  override chapterMode = ChapterMode.MangaAjax;
}
