// Port of keiyoushi/extensions-source src/en/hunlightcomics/HunlightComics.kt (generated by tools/generate.ts)
import { ChapterMode, Madara } from "../../../themes/madara/index.ts";

export default class HunlightComics extends Madara {
  override chapterMode = ChapterMode.MangaAjax;
}
