// Generated by tools/messages.ts from upstream manhwaz/assets/i18n. Do not edit.
import type { Messages } from "../../sdk/i18n.ts";

export const messages: Messages = {
  "en": {
    "filter_ignored_warning": "Ignored when using text search",
    "cannot_use_order_by_warning": "Cannot use \"Order by\" filter when genre is \"%s\" or \"%s\"",
    "genre_fetch_failed": "Failed to fetch genres",
    "genre_missing_warning": "Press \"Reset\" to attempt to show genres",
    "genre_filter_title": "Genre",
    "genre_all": "All",
    "genre_completed": "Completed",
    "order_by_filter_title": "Order by",
    "order_by_latest": "Latest",
    "order_by_rating": "Rating",
    "order_by_most_views": "Most views",
    "order_by_new": "New"
  },
  "vi": {
    "filter_ignored_warning": "Không thể dùng chung với tìm kiếm bằng từ khoá",
    "cannot_use_order_by_warning": "Không thể sắp xếp nếu chọn thể loại là \"%s\" hoặc \"%s\"",
    "genre_fetch_failed": "Đã có lỗi khi tải thể loại",
    "genre_missing_warning": "Chọn \"Đặt lại\" để hiển thị thể loại",
    "genre_filter_title": "Thể loại",
    "genre_all": "Tất cả",
    "genre_completed": "Hoàn thành",
    "order_by_filter_title": "Sắp xếp theo",
    "order_by_latest": "Mới nhất",
    "order_by_rating": "Đánh giá cao",
    "order_by_most_views": "Xem nhiều",
    "order_by_new": "Mới"
  }
};
