// Port of keiyoushi/extensions-source src/all/yaoimangaonline/Filters.kt
import { Filter } from "../../../sdk/index.ts";

const categories = new Map<string, string>([
  ["ALL", "-1"],
  ["07-Ghost dj", "121"],
  ["A3! Dj", "5315"],
  ["Ace Attorney Dj", "5899"],
  ["Ai no Kusabi DJ", "87"],
  ["AI: The Somnium Files Dj", "6774"],
  ["Aldnoah.Zero Dj", "4978"],
  ["All Out!! Dj", "3414"],
  ["Ameiro Paradox Dj", "1741"],
  ["Ansatsu Kyoushitsu Dj", "3437"],
  ["Antique Bakery dj", "123"],
  ["Ao no Exorcist Dj", "639"],
  ["Arashi Dj", "2518"],
  ["Arslan Senki Dj", "5098"],
  ["Assassination Classroom Dj", "2522"],
  ["Assassin's Creed Dj", "2519"],
  ["Astro Fighter Sunred Dj", "348"],
  ["Attack on Titan dj", "108"],
  ["Avengers Dj", "2532"],
  ["Azazel san! dj", "214"],
  ["Baccano Dj", "5925"],
  ["Bakumatsu Rock Dj", "2552"],
  ["Banana Fish Dj", "5926"],
  ["Band Yarouze! Dj", "3941"],
  ["Bara", "14"],
  ["Barakamon dj", "132"],
  ["Basquash! Dj", "2550"],
  ["Batman Dj", "7861"],
  ["Battle Spirits Dj", "2555"],
  ["Beelzebub dj", "125"],
  ["Berserk Dj", "2558"],
  ["Beyblade Burst Dj", "3512"],
  ["Big Hero 6 Dj", "3464"],
  ["Black Clover Dj", "5924"],
  ["Black Jack Dj", "4006"],
  ["Blazblue Dj", "351"],
  ["Blood Blockade Battlefront Dj", "3987"],
  ["Boktai Dj", "1307"],
  ["Boku Dake ga Inai Machi Dj", "3529"],
  ["Boku no Hero Academia Dj", "3362"],
  ["Boondock Saints Dj", "2620"],
  ["Border Dj", "2617"],
  ["Brave Story Dj", "2622"],
  ["Buddy Complex Dj", "2625"],
  ["Bungou Stray Dogs Dj", "5897"],
  ["Bungou to Alchemist Dj", "6365"],
  ["Call of Duty Modern Warfare DJ", "2794"],
  ["Candidate for Goddess Dj", "2627"],
  ["Cardfight!! Vanguard Dj", "3611"],
  ["Casshern Sins Dj", "2628"],
  ["Castlevania Dj", "2631"],
  ["Chinko no Tsubuyaki Dj", "2865"],
  ["Chobits Dj", "2546"],
  ["Chouhatsu Denkou Sekka Boys Dj", "4977"],
  ["Chousoku Henkei Gyrozetter Dj", "2633"],
  ["Clannad Dj", "2635"],
  ["Cluster Edge Dj", "2640"],
  ["Code Geass Dj", "2644"],
  ["ConCon-Collector Dj", "478"],
  ["Crows ZERO Dj", "3331"],
  ["D.Gray-man Dj", "2255"],
  ["Daiya no Ace Dj", "2676"],
  ["Danganronpa Dj", "3712"],
  ["Dark Avengers Dj", "2529"],
  ["Darkstalkers/ Red Earth dj", "383"],
  ["Datenshi ni Sasageru Uta dj", "949"],
  ["DAYS Dj", "3514"],
  ["Dead by Daylight Dj", "4970"],
  ["Detective Conan Dj", "3333"],
  ["Devil May Cry 5 Dj", "5915"],
  ["Devilman Dj", "4975"],
  ["Donten ni Warau Dj", "3922"],
  ["Doushitemo Furetakunai Dj", "3052"],
  ["Dr. Stone Dj", "7324"],
  ["Dragalia Lost Dj", "5914"],
  ["Dragon Ball Dj", "2799"],
  ["Dragon Quest Dj", "398"],
  ["Dragon's Dogma Dj", "3679"],
  ["DRAMAtical Murder Dj", "3486"],
  ["Drifters Dj", "5930"],
  ["Durarara dj", "82"],
  ["Dynasty Warriors Dj", "3218"],
  ["Enen no Shouboutai Dj", "5933"],
  ["Ensemble Stars! Dj", "1868"],
  ["Enzai Dj", "571"],
  ["Eternal Arcadia Dj", "2825"],
  ["Eyeshield 21 Dj", "3644"],
  ["Fantastic Boyfriends Dj", "1704"],
  ["Fate/Grand Order Dj", "3117"],
  ["Fate/Stay Night Dj", "3656"],
  ["Fate/Zero Dj", "3235"],
  ["Final Fantasy Dj", "3277"],
  ["Fire Emblem Dj", "692"],
  ["Free! dj", "71"],
  ["Friday the 13th Dj", "3944"],
  ["Fullmetal Alchemist Dj", "409"],
  ["Furry", "15"],
  ["Future Card Buddyfight Dj", "387"],
  ["Gay Novels", "1852"],
  ["Gekkan Shoujo Nozaki-kun Dj", "3940"],
  ["Genshin Impact Dj", "6423"],
  ["GetBackers Dj", "5278"],
  ["Giant Killing Dj", "3216"],
  ["Gingitsune Dj", "325"],
  ["Gintama Dj", "3225"],
  ["Golden Kamuy Dj", "5901"],
  ["Granblue Fantasy Dj", "3758"],
  ["Gravitation Dj", "2069"],
  ["Gravity Falls Dj", "3855"],
  ["Guardians of the Galaxy Dj", "449"],
  ["Gugure! Kokkuri-san Dj", "3869"],
  ["Gundam Dj", "5931"],
  ["Gundam Wing Dj", "5900"],
  ["Gyakuten Saiban Dj", "2834"],
  ["Hacka Doll Dj", "3472"],
  ["Haikyuu!! Dj", "512"],
  ["Hakkenden Dj", "2498"],
  ["Hakuouki Dj", "2495"],
  ["Harry Potter Dj", "2489"],
  ["Hataraku Saibou Dj", "4191"],
  ["Heat Guy J Dj", "2482"],
  ["Heroman Dj", "2479"],
  ["Hetalia Dj", "191"],
  ["Hidoku Shinaide Dj", "754"],
  ["Hikaru No Go Dj", "2476"],
  ["Hinomaru Zumou Dj", "2473"],
  ["Honeycomb Child Dj", "306"],
  ["Hoozuki no Reitetsu Dj", "3810"],
  ["How to Train Your Dragon Dj", "196"],
  ["Hunter x Hunter Dj", "3562"],
  ["Hypnosis Mic Dj", "4289"],
  ["Identity V Dj", "5929"],
  ["IDOLiSH7 Dj", "3773"],
  ["Inazuma Eleven Dj", "2279"],
  ["Initial D Dj", "2464"],
  ["Interval Dj", "2462"],
  ["InuYasha Dj", "2455"],
  ["Ixion Saga Dj", "2454"],
  ["Jinrou Judgement Dj", "7862"],
  ["Jojo DJ", "1280"],
  ["Jojo no Kimyou na Bouken Dj", "3193"],
  ["Jormungand Dj", "6228"],
  ["Jujutsu Kaisen Dj", "5895"],
  ["K Project Dj", "1014"],
  ["Kagerou Project Dj", "4094"],
  ["Kaiji Dj", "2828"],
  ["Kakumeiki Valvrave Dj", "2450"],
  ["Kami-sama no Ude no Naka de Dj", "3056"],
  ["Kanpai! Dj", "2445"],
  ["Kantai Collection Dj", "3664"],
  ["Karamete de Kudoite Dj", "1933"],
  ["Katekyo Hitman Reborn! Dj", "2247"],
  ["Katekyo! Dj", "1843"],
  ["Kekkai Sensen Dj", "3695"],
  ["Kichiku Megane Dj", "3816"],
  ["Kidou Senshi Gundam – Tekketsu no Orphans Dj", "3129"],
  ["Kill la Kill Dj", "2447"],
  ["Killing Stalking Dj", "6593"],
  ["Kimetsu no Yaiba Dj", "5898"],
  ["Kimi no Na wa dj", "5423"],
  ["Kimi to boku Dj", "2442"],
  ["King of Fighters Dj", "6255"],
  ["King of Prism by Pretty Rhythm Dj", "4973"],
  ["King's Raid Dj", "4969"],
  ["Kingdom Hearts Dj", "2269"],
  ["Kiseijuu Dj", "2996"],
  ["Knight's & Magic Dj", "3736"],
  ["Kocchi Muite Waratte Dj", "3238"],
  ["Koibito Kijunchi Dj", "882"],
  ["Koisuru Boukun Dj", "1004"],
  ["Konjiki no Gash!! Dj", "3892"],
  ["Kono Yoru no Subete Dj", "2440"],
  ["Koshotengai no Hashihime Dj", "4968"],
  ["Kuroko no Basuke Dj", "1094"],
  ["Kuroshitsuji Dj", "2252"],
  ["Kyoukai no Kanata Dj", "2434"],
  ["Kyoushou Sentai Danjijaa Dj", "3303"],
  ["Lamento dj", "150"],
  ["Laputa Castle in the Sky Dj", "2432"],
  ["League of Legends Dj", "455"],
  ["Legendz: Tale of the Dragon Kings Dj", "343"],
  ["Liar Game Dj", "2430"],
  ["Love Live! Dj", "3779"],
  ["Love Stage!! Dj", "2425"],
  ["Lucky Star dj", "147"],
  ["Macross Dj", "2423"],
  ["Magic Kaito Dj", "4966"],
  ["Magical x Miracle Dj", "2419"],
  ["Majin Tantei Nougami Neuro Dj", "2417"],
  ["Marginal#4 Dj", "3483"],
  ["Marvel Dj", "2527"],
  ["Meganebu! Dj", "2822"],
  ["Meganoido Dj", "2414"],
  ["Mobile Legends Dj", "6425"],
  ["Monster Hunter Dj", "2411"],
  ["Moritaka Dj", "2409"],
  ["Moteki Dj", "2407"],
  ["Mushishi Dj", "2406"],
  ["Muv-Luv Dj", "2404"],
  ["My Hero Academia Dj", "3363"],
  ["Nabari no Ou dj", "145"],
  ["Natsume Yuujinchou Dj", "2401"],
  ["Neon Genesis Evangelion Dj", "3157"],
  ["Nier Automata Dj", "3743"],
  ["Nighthead Dj", "2399"],
  ["Nijisanji Dj", "6594"],
  ["Nikaidou Shachiku no Nikki Dj", "2397"],
  ["No.6 Dj", "2394"],
  ["Nobunagun Dj", "2391"],
  ["Noblesse Dj", "2389"],
  ["Nodame Cantabile Dj", "2388"],
  ["Nurarihyon no Mago Dj", "2386"],
  ["Ookiku Furikabutte Dj", "3231"],
  ["One Piece Dj", "2383"],
  ["One Punch Man Dj", "3364"],
  ["Onoda Dj", "2271"],
  ["Osomatsu-san Dj", "2380"],
  ["Otome Youkai Zakuro Dj", "2378"],
  ["Ouran Koukou Host Club Dj", "2376"],
  ["Over the Garden Wall Dj", "4971"],
  ["Overlord Dj", "3766"],
  ["Owari no Seraph Dj", "3765"],
  ["Owarimonogatari Dj", "2373"],
  ["Pandora Hearts Dj", "2370"],
  ["Persona Dj", "1700"],
  ["Pokemon Dj", "2366"],
  ["Pokémon Dj", "2367"],
  ["Prince of Stride Dj", "3759"],
  ["Prince of Tennis Dj", "2336"],
  ["Professor Layton Dj", "2332"],
  ["Promare Dj", "4280"],
  ["Psycho Break Dj", "1967"],
  ["Psycho Pass Dj", "5910"],
  ["Pumpkin Scissors Dj", "2231"],
  ["Punishing: Gray Raven Dj", "5896"],
  ["Quiz Magic Academy Dj", "5981"],
  ["Rakudai Ninja Rantarou Dj", "1911"],
  ["Rampo Kitan: Game of Laplace Dj", "3417"],
  ["Re: Zero kara Hajimeru Isekai Seikatsu Dj", "5935"],
  ["Resident Evil Dj", "2832"],
  ["Rival Schools Dj", "2844"],
  ["Rokkuman Dj", "2229"],
  ["Rurouni Kenshin Dj", "2226"],
  ["Ryu ga Gotoku Dj", "6335"],
  ["Sabita Yoru demo Koi wa Sasayaku Dj", "1465"],
  ["Saiki Kusuo no Psi Nan Dj", "3851"],
  ["Saint Seiya Dj", "7860"],
  ["Saint Young Men Dj", "2223"],
  ["Saiyuki Dj", "5905"],
  ["Sakura Gari Dj", "734"],
  ["Samurai Deeper Kyo Dj", "2220"],
  ["Sekaiichi Hatsukoi Dj", "2379"],
  ["Sengoku Basara Dj", "3250"],
  ["Sherlock Dj", "1710"],
  ["Shiki Dj", "2323"],
  ["Shin SangokuMusou Dj", "3217"],
  ["Shin Seiki Evangelion Dj", "3156"],
  ["Shingeki no Kyojin dj", "97"],
  ["Shining Wind Dj", "461"],
  ["Shinkansen Henkei Robo Shinkalion Dj", "5908"],
  ["Shinrabansou Choco Dj", "2820"],
  ["Shironeko Project Dj", "2321"],
  ["Shokugeki no Soma Dj", "5907"],
  ["Shoshitsu Dj", "2318"],
  ["Show by Rock!! Dj", "3906"],
  ["ShuMao Dj", "2218"],
  ["Silver Spoon Dj", "4074"],
  ["SK8 the Infinity Dj", "7178"],
  ["Slam Dunk Dj", "6104"],
  ["SMAP! Dj", "2987"],
  ["Smile PreCure! dj", "370"],
  ["Soukyuu no Fafner Dj", "2216"],
  ["SOUL CATCHER", "5904"],
  ["Soul Eater Dj", "2314"],
  ["Soul Hackers Dj", "2313"],
  ["SoulCalibur Dj", "2312"],
  ["South Park Dj", "4030"],
  ["Splatoon Dj", "2377"],
  ["SSSS.GRIDMAN Dj", "5903"],
  ["Star Fox Dj", "417"],
  ["Stardew Valley Dj", "5932"],
  ["Starry Sky Dj", "2211"],
  ["Strange Plus Dj", "2212"],
  ["Street Fighter Dj", "3769"],
  ["Strider Hiryuu Dj", "2214"],
  ["Suisei no Gargantia Dj", "3245"],
  ["Summer Wars Dj", "2797"],
  ["Superman/Batman Dj", "49"],
  ["Supernatural Dj", "1705"],
  ["SWAT Kats Dj", "3283"],
  ["Sword Art Online dj", "185"],
  ["Tactics dj", "182"],
  ["Taiiku Kyoushi Kiwame Dj", "3806"],
  ["Tales of Destiny Dj", "5902"],
  ["Tales of Graces dj", "180"],
  ["Tales of the Abyss Dj", "4073"],
  ["Tales of Vesperia Dj", "3931"],
  ["Tales of Zestiria Dj", "4976"],
  ["Tate no Yuusha no Nariagari Dj", "4967"],
  ["The Evil Within Dj", "1966"],
  ["THE IDOLM@STER Dj", "3558"],
  ["The Legend Of Zelda Dj", "4455"],
  ["The Lion King DJ", "320"],
  ["The Melancholy of Haruhi Suzumiya Dj", "3823"],
  ["The Mighty Thor Dj", "2082"],
  ["The Outsiders Dj", "576"],
  ["The Silence of the Lambs Dj", "5982"],
  ["The Unlimited – Hyoubu Kyousuke Dj", "834"],
  ["The World God Only Knows Dj", "3667"],
  ["Tiger & Bunny dj", "61"],
  ["To Aru Majutsu no Index Dj", "2079"],
  ["Tobaku Haouden ZERO Dj", "3927"],
  ["Togainu no Chi dj", "46"],
  ["Tokkyuu!! Dj", "2077"],
  ["Tokyo Ghoul Dj", "1756"],
  ["Toriko Dj", "2812"],
  ["Totally Captivated dj", "178"],
  ["Touken Ranbu Dj", "570"],
  ["Trigun Dj", "174"],
  ["Turn A Gundam Dj", "2480"],
  ["Twisted Wonderland Dj", "5909"],
  ["Uchuu Kyoudai Dj", "6052"],
  ["Under Grand Hotel Dj", "3048"],
  ["Ura Brave Kingdom Dj", "2074"],
  ["Urban Reign Dj", "2846"],
  ["Usavich dj", "47"],
  ["Uta no Prince-sama Dj", "2259"],
  ["Utawarerumono Dj", "230"],
  ["Valkariya Chronicles Dj", "2806"],
  ["Valkyria Chronicles Dj", "225"],
  ["Valvrave the Liberator Dj", "2449"],
  ["Vampire Knight dj", "171"],
  ["Vassalord dj", "166"],
  ["Vinland Saga Dj", "6424"],
  ["Vocaloid Dj", "1719"],
  ["Voltron Dj", "5414"],
  ["Warriors Orochi Dj", "218"],
  ["Wild Adapter dj", "164"],
  ["Winnie the Pooh Dj", "3869"],
  ["World Trigger Dj", "1091"],
  ["xxxHoLic Dj", "1075"],
  ["Yahari Ore no Seishun Love Comedy wa Machigatteiru Dj", "5916"],
  ["Yakuza DJ", "161"],
  ["Yami no Matsuei Dj", "6106"],
  ["Yaoi DJ", "1"],
  ["Yaoi Gallery", "198"],
  ["Yaoi Games Online", "199"],
  ["Yaoi Magazines", "3543"],
  ["Yaoi Manga", "13"],
  ["Yaoi Oneshots", "22"],
  ["Yarichin Bitch Club Dj", "5927"],
  ["Yarou Fes 2013 Petit Dj", "3433"],
  ["Yondemasuyo Azazel-san dj", "210"],
  ["Young Black Jack dj", "207"],
  ["Yowamushi Pedal Dj", "2273"],
  ["Yu Yu Hakusho Dj", "1087"],
  ["Yu-Gi-Oh! Dj", "1027"],
  ["Yuri!!! on Ice Dj", "2503"],
  ["Zettai Karen Children dj", "50"],
  ["Zootopia Dj", "2075"],
]);

export class CategoryFilter extends Filter.Select<string> {
  constructor(values: string[] = [...categories.keys()]) {
    super("Category", values);
  }
  toString() {
    return categories.get(this.values[this.state])!;
  }
}

const tags = new Map<string, string>([
  ["ALL", ""],
  ["Ahegao", "ahegao"],
  ["Bara", "bara"],
  ["BDSM Yaoi", "bdsm"],
  ["Beastality", "beastality"],
  ["Big Penis", "big-penis"],
  ["Blowjob", "blowjob"],
  ["Bondage", "bondage"],
  ["Chinese", "chinese"],
  ["Comedy", "comedy"],
  ["Completed Yaoi Manga", "completed-yaoi-manga"],
  ["Cross-dressing", "cross-dressing"],
  ["Cute", "cute"],
  ["Dark skin", "dark-skin"],
  ["Drama", "drama"],
  ["English", "english"],
  ["Full Color", "full-color"],
  ["Group Sex", "group-sex"],
  ["Handjob", "handjob"],
  ["Hardcore", "hardcore"],
  ["Hard Yaoi", "hard-yaoi"],
  ["Hentai", "hentai"],
  ["Hentai Yaoi", "hentai-yaoi"],
  ["Hentai Yaoi Manga", "hentai-yaoi-manga"],
  ["Incest", "incest"],
  ["Japanese", "japanese"],
  ["Komik Yaoi Hentai", "komik-yaoi-hentai"],
  ["Korean", "korean"],
  ["Masturbation", "masturbation"],
  ["Megane", "megane"],
  ["Muscle", "muscle"],
  ["Nipple play", "nipple-play"],
  ["Rape", "rape"],
  ["Romance", "romance"],
  ["School Life", "school-life"],
  ["Sex toy", "sex-toy"],
  ["Shounen Ai", "shounen-ai"],
  ["Slice of Life", "slice-of-life"],
  ["Smut", "smut"],
  ["Threesome", "threesome"],
  ["Uncensored Yaoi", "uncensored-yaoi"],
  ["Webtoon", "webtoon"],
  ["Yaoi", "yaoi"],
  ["Yaoi Hentai", "yaoi-hentai"],
  ["Yaoi Hentai Manga", "yaoi-hentai-manga"],
  ["Yaoi Sex", "yaoi-sex"],
]);

export class TagFilter extends Filter.Select<string> {
  constructor(values: string[] = [...tags.keys()]) {
    super("Tag", values);
  }
  toString() {
    return tags.get(this.values[this.state])!;
  }
}

