// Port of keiyoushi/extensions-source src/en/erosscans/ErosScans.kt (generated by tools/generate.ts)
import { ClientBuilder } from "../../../sdk/index.ts";
import { MangaThemesia } from "../../../themes/mangathemesia/index.ts";

export default class ErosScans extends MangaThemesia {
  protected override configureClient(b: ClientBuilder) {
    b.rateLimit(3, 1000);
    return b;
  }

  protected override configureHeaders(h: Headers) {
    h.delete("Origin");
    return h;
  }
}
