// Port of keiyoushi/extensions-source src/en/linkmanga/LinkManga.kt (generated by tools/generate.ts)
import { Madara } from "../../../themes/madara/index.ts";

export default class LinkManga extends Madara {}
