// Port of keiyoushi/extensions-source src/en/yaoiscan/YaoiScan.kt (generated by tools/generate.ts)
import { Madara } from "../../../themes/madara/index.ts";

export default class YaoiScan extends Madara {}
