// Port of keiyoushi/extensions-source src/en/violetscans/VioletScans.kt (generated by tools/generate.ts)
import { MangaThemesia } from "../../../themes/mangathemesia/index.ts";

export default class VioletScans extends MangaThemesia {
  override mangaUrlDirectory = "/comics";

  override searchMangaSelector() {
    return ".utao .uta .imgu, .listupd .bs .bsx:not(:has(.novelabel)), .listo .bs .bsx:not(:has(.novelabel))";
  }

  override chapterListSelector() {
    return "#chapterlist li:not(:has(svg))";
  }

  override seriesAltNameSelector = ".alternative .desktop-titles";
}
