// Port of keiyoushi/extensions-source src/id/mgkomik/MGKomik.kt (generated by tools/generate.ts)
import { DateTimeFormatter, Locale } from "../../../sdk/index.ts";
import { MadaraNoAjax } from "../../../themes/madara/index.ts";

export default class MGKomik extends MadaraNoAjax {
  override chapterDateFormat = DateTimeFormatter.ofPattern("dd MMM yy", Locale.US);

  override mangaSubString = "komik";

  override genreDirectory = "genres";

  protected override configureHeaders(h: Headers) {
    h.set("Sec-CH-UA-Model", "\"\"");
    h.set("Sec-CH-UA-Platform", "\"\"");
    return h;
  }

  override mangaDetailsSelectorDescription = "div.description-summary div.summary__content p";
}
