// Port of keiyoushi/extensions-source src/en/bunmanga/BunManga.kt (generated by tools/generate.ts)
import { Madara } from "../../../themes/madara/index.ts";

export default class BunManga extends Madara {}
