// Port of keiyoushi/extensions-source src/en/orchisasia/Orchisasia.kt (generated by tools/generate.ts)
import { Madara } from "../../../themes/madara/index.ts";

export default class Orchisasia extends Madara {
  override mangaSubString = "comic";
}
