// Port of keiyoushi/extensions-source src/all/mangacrazy/MangaCrazy.kt (generated by tools/generate.ts)
import { ChapterMode, Madara } from "../../../themes/madara/index.ts";

export default class MangaCrazy extends Madara {
  override chapterMode = ChapterMode.MangaAjax;
}
