// Port of keiyoushi/extensions-source src/en/toonizy/Toonizy.kt (generated by tools/generate.ts)
import { Madara } from "../../../themes/madara/index.ts";

export default class Toonizy extends Madara {}
