// Port of keiyoushi/extensions-source src/id/noromax/Noromax.kt (generated by tools/generate.ts)
import { MangaThemesia } from "../../../themes/mangathemesia/index.ts";

export default class Noromax extends MangaThemesia {
  override hasProjectPage = true;

  override pageSelector = "div#readerarea img:not(noscript img)";
}
