// Port of keiyoushi/extensions-source src/id/doujinku/Doujinku.kt (generated by tools/generate.ts)
import { MangaThemesia } from "../../../themes/mangathemesia/index.ts";

export default class Doujinku extends MangaThemesia {
  override datePattern = "d MMMM yyyy";
}
