// Port of keiyoushi/extensions-source src/en/wuxiaworld/WuxiaWorld.kt (generated by tools/generate.ts)
import { ChapterMode, Madara } from "../../../themes/madara/index.ts";

export default class WuxiaWorld extends Madara {
  override mangaSubString = "novel";

  override chapterMode = ChapterMode.MangaAjax;
}
