// Port of keiyoushi/extensions-source src/en/octopusmanga/OctopusManga.kt (generated by tools/generate.ts)
import { ChapterMode, Madara } from "../../../themes/madara/index.ts";

export default class OctopusManga extends Madara {
  override chapterMode = ChapterMode.MangaAjax;
}
