// Port of keiyoushi/extensions-source src/en/cocomic/Cocomic.kt (generated by tools/generate.ts)
import { ClientBuilder } from "../../../sdk/index.ts";
import { ChapterMode, Madara } from "../../../themes/madara/index.ts";

export default class Cocomic extends Madara {
  protected override configureClient(b: ClientBuilder) {
    b.rateLimit(1, 2000, (it: URL) => !it.pathname.startsWith("/wp-content/uploads/"));
    return b;
  }

  override chapterMode = ChapterMode.MangaAjax;

  override chapterListSelector() {
    return "li.wp-manga-chapter:not(.premium)";
  }
}
