// Port of keiyoushi/extensions-source src/en/zinmanga/Zinmanga.kt (generated by tools/generate.ts)
import { Madara } from "../../../themes/madara/index.ts";

export default class Zinmanga extends Madara {
  override filterNonMangaItems = false;
}
