// Generated by tools/messages.ts from upstream keyoapp/assets/i18n. Do not edit.
import type { Messages } from "../../sdk/i18n.ts";

export const messages: Messages = {
  "ar": {
    "pref_show_paid_chapter_title": "عرض الفصول المدفوعة",
    "pref_show_paid_chapter_summary_on": "سيتم عرض الفصول المدفوعة",
    "pref_show_paid_chapter_summary_off": "سيتم عرض الفصول المجانية فقط.",
    "chapter_page_url_not_found": "رابط الصفحة غير موجود"
  },
  "en": {
    "alt_names_heading": "Alternative Titles:",
    "pref_show_paid_chapter_title": "Display paid chapters",
    "pref_show_paid_chapter_summary_on": "Paid chapters will appear.",
    "pref_show_paid_chapter_summary_off": "Only free chapters will be displayed.",
    "chapter_page_url_not_found": "Page URL not found"
  },
  "fr": {
    "pref_show_paid_chapter_title": "Afficher les chapitres payants",
    "pref_show_paid_chapter_summary_on": "Les chapitres payants apparaitront.",
    "pref_show_paid_chapter_summary_off": "Seuls les chapitres gratuits apparaitront.",
    "chapter_page_url_not_found": "Page URL non trouvée"
  }
};
