// Port of keiyoushi/extensions-source src/id/kanzenin/Kanzenin.kt (generated by tools/generate.ts)
import { MangaThemesia } from "../../../themes/mangathemesia/index.ts";

export default class Kanzenin extends MangaThemesia {}
