// Port of keiyoushi/extensions-source src/en/apcomics/Apcomics.kt (generated by tools/generate.ts)
import { ChapterMode, Madara } from "../../../themes/madara/index.ts";

export default class Apcomics extends Madara {
  override chapterMode = ChapterMode.MangaAjax;
}
