// Port of keiyoushi/extensions-source src/en/arenascans/ArenaScans.kt (generated by tools/generate.ts)
import { MangaThemesia } from "../../../themes/mangathemesia/index.ts";

export default class ArenaScans extends MangaThemesia {}
