// Port of keiyoushi/extensions-source src/en/rackus/Rackus.kt (generated by tools/generate.ts)
import { MangaThemesia } from "../../../themes/mangathemesia/index.ts";

export default class Rackus extends MangaThemesia {}
