// Port of keiyoushi/extensions-source src/all/manhwadashraw/ManhwaDashRaw.kt (generated by tools/generate.ts)
import { DateTimeFormatter, Locale } from "../../../sdk/index.ts";
import { MadaraNoAjax } from "../../../themes/madara/index.ts";

export default class ManhwaDashRaw extends MadaraNoAjax {
  override chapterDateFormat = DateTimeFormatter.ofPattern("dd/MM/yyyy", Locale.ROOT);

  override mangaDetailsSelectorStatus = "div.post-content_item:contains(Status) > div.summary-content";

  override mangaDetailsSelectorDescription = "div.post-content_item:contains(Summary) div.summary-container";

  override pageListParseSelector = "div.page-break img.wp-manga-chapter-img";
}
