// Port of keiyoushi/extensions-source src/en/mangamaniacs/MangaManiacs.kt (generated by tools/generate.ts)
import { Madara } from "../../../themes/madara/index.ts";

export default class MangaManiacs extends Madara {}
