// Port of keiyoushi/extensions-source src/en/spmanhwa/Spmanhwa.kt (generated by tools/generate.ts)
import { Madara } from "../../../themes/madara/index.ts";

export default class Spmanhwa extends Madara {}
