// Port of keiyoushi/extensions-source src/en/mangakiss/MangaKiss.kt (generated by tools/generate.ts)
import { Madara } from "../../../themes/madara/index.ts";

export default class MangaKiss extends Madara {}
