// Port of keiyoushi/extensions-source src/en/manhwatop/Manhwatop.kt (generated by tools/generate.ts)
import { ChapterMode, Madara } from "../../../themes/madara/index.ts";

export default class Manhwatop extends Madara {
  override chapterMode = ChapterMode.MangaAjax;

  override filterNonMangaItems = false;
}
