// Port of keiyoushi/extensions-source src/en/dragontea/DragonTea.kt (generated by tools/generate.ts)
import { ClientBuilder, DateTimeFormatter, Locale } from "../../../sdk/index.ts";
import { ChapterMode, Madara } from "../../../themes/madara/index.ts";

export default class DragonTea extends Madara {
  override chapterDateFormat = DateTimeFormatter.ofPattern("MM/dd/yyyy", Locale.US);

  override mangaSubString = "novel";

  override chapterMode = ChapterMode.MangaAjax;

  protected override configureClient(b: ClientBuilder) {
    b.rateLimit(1, 1000, (it: URL) => !it.pathname.startsWith("/wp-content/uploads/"));
    return b;
  }
}
