// Generated by tools/messages.ts from upstream mangaplus/assets/i18n. Do not edit.
import type { Messages } from "../../../sdk/i18n.ts";

export const messages: Messages = {
  "en": {
    "chapter_expired": "The chapter reading period has expired.",
    "image_quality": "Image quality",
    "image_quality_high": "High",
    "image_quality_low": "Low",
    "image_quality_medium": "Medium",
    "not_available": "Title not available in this language.",
    "split_double_pages": "Split double pages",
    "split_double_pages_summary": "Only a few titles supports disabling this setting.",
    "subtitle_only": "Show subtitle only",
    "subtitle_only_summary": "Removes the redundant chapter number from the chapter name.",
    "title_removed": "This title was removed from the MANGA Plus catalogue.",
    "unknown_error": "An unknown error happened."
  },
  "pt-BR": {
    "chapter_expired": "O período de leitura do capítulo expirou.",
    "image_quality": "Qualidade da imagem",
    "image_quality_high": "Alta",
    "image_quality_low": "Baixa",
    "image_quality_medium": "Média",
    "not_available": "Título não disponível neste idioma.",
    "split_double_pages": "Dividir as páginas duplas",
    "split_double_pages_summary": "Somente poucos títulos suportam a desativação desta configuração.",
    "title_removed": "Este título foi removido do catálogo do MANGA Plus.",
    "unknown_error": "Um erro desconhecido ocorreu."
  },
  "vi": {
    "chapter_expired": "Đã hết thời gian đọc chương này.",
    "image_quality": "Chất lượng ảnh",
    "image_quality_high": "Cao",
    "image_quality_low": "Thấp",
    "image_quality_medium": "Vừa",
    "not_available": "Truyện không có sẵn ở ngôn ngữ này.",
    "split_double_pages": "Tách trang đôi",
    "split_double_pages_summary": "Chỉ một số truyện hỗ trợ không tách trang đôi.",
    "title_removed": "Truyện này đã bị gỡ khỏi MANGA Plus.",
    "unknown_error": "Đã xảy ra lỗi không xác định."
  }
};
