// Port of keiyoushi/extensions-source src/en/manhuaus/ManhuaUS.kt (generated by tools/generate.ts)
import { ChapterMode, Madara } from "../../../themes/madara/index.ts";

export default class ManhuaUS extends Madara {
  override filterNonMangaItems = false;

  override chapterMode = ChapterMode.MangaAjax;
}
