// Port of keiyoushi/extensions-source src/en/allporncomicio/AllPornComicIo.kt (generated by tools/generate.ts)
import { DateTimeFormatter, Locale } from "../../../sdk/index.ts";
import { ChapterMode, Madara } from "../../../themes/madara/index.ts";

export default class AllPornComicIo extends Madara {
  override chapterDateFormat = DateTimeFormatter.ofPattern("dd/MM/yyyy", Locale.ROOT);

  override chapterMode = ChapterMode.MangaAjax;
}
