// Port of keiyoushi/extensions-source src/id/sasangeyou/Sasangeyou.kt (generated by tools/generate.ts)
import { MangaThemesia } from "../../../themes/mangathemesia/index.ts";

export default class Sasangeyou extends MangaThemesia {
  override datePattern = "MM/dd/yyyy";

  override hasProjectPage = false;
}
