// Port of keiyoushi/extensions-source src/en/ksgroupscans/KSGroupScans.kt (generated by tools/generate.ts)
import { ChapterMode, Madara } from "../../../themes/madara/index.ts";

export default class KSGroupScans extends Madara {
  override chapterMode = ChapterMode.MangaAjax;
}
