// Port of keiyoushi/extensions-source src/en/manhwacomics/ManhwaComics.kt (generated by tools/generate.ts)
import { DateTimeFormatter, Locale } from "../../../sdk/index.ts";
import { ChapterMode, Madara } from "../../../themes/madara/index.ts";

export default class ManhwaComics extends Madara {
  override mangaSubString = "manhwa";

  override chapterMode = ChapterMode.MangaAjax;

  override chapterDateFormat = DateTimeFormatter.ofPattern("d MMM yyyy", Locale.US);
}
