// Port of keiyoushi/extensions-source src/en/ravenscans/RavenScans.kt (generated by tools/generate.ts)
import { MangaThemesia } from "../../../themes/mangathemesia/index.ts";

export default class RavenScans extends MangaThemesia {
  override mangaUrlDirectory = "/manga";
}
