// Port of keiyoushi/extensions-source src/en/akazascans/AkazaScans.kt (generated by tools/generate.ts)
import { MangaThemesia } from "../../../themes/mangathemesia/index.ts";

export default class AkazaScans extends MangaThemesia {}
