// Port of keiyoushi/extensions-source src/en/manhuazonghe/ManhuaZonghe.kt (generated by tools/generate.ts)
import { Madara } from "../../../themes/madara/index.ts";

export default class ManhuaZonghe extends Madara {
  override filterNonMangaItems = false;

  override mangaSubString = "manhua";
}
