// Port of keiyoushi/extensions-source src/en/hentaisco/HentaiSco.kt (generated by tools/generate.ts)
import { MadaraNoAjax } from "../../../themes/madara/index.ts";

export default class HentaiSco extends MadaraNoAjax {
  override mangaSubString = "hentai";
}
