// Port of keiyoushi/extensions-source src/en/manhuatop/ManhuaTop.kt (generated by tools/generate.ts)
import { DateTimeFormatter, Locale } from "../../../sdk/index.ts";
import { ChapterMode, Madara } from "../../../themes/madara/index.ts";

export default class ManhuaTop extends Madara {
  override chapterMode = ChapterMode.MangaAjax;

  override chapterDateFormat = DateTimeFormatter.ofPattern("MM/dd/yyyy", Locale.ROOT);

  override mangaSubString = "manhua";

  override filterNonMangaItems = false;
}
