// Port of keiyoushi/extensions-source src/en/mahouirexnohentaikarte/Mahouirexnohentaikarte.kt (generated by tools/generate.ts)
import { ChapterMode, Madara } from "../../../themes/madara/index.ts";

export default class Mahouirexnohentaikarte extends Madara {
  override chapterMode = ChapterMode.MangaAjaxQuery;
}
