// Port of keiyoushi/extensions-source src/en/mangatx/MangaTX.kt (generated by tools/generate.ts)
import { ClientBuilder } from "../../../sdk/index.ts";
import { MangaThemesia } from "../../../themes/mangathemesia/index.ts";

export default class MangaTX extends MangaThemesia {
  override mangaUrlDirectory = "/manga-list";

  override datePattern = "dd-MM-yyyy";

  protected override configureClient(b: ClientBuilder) {
    b.rateLimit(3, 1000);
    return b;
  }

  override seriesAuthorSelector = ".imptdt:contains(Author) a";

  override get supportsRelatedMangas() {
    return false;
  }
}
