// Port of keiyoushi/extensions-source src/en/zinmanganet/ZinmangaNet.kt (generated by tools/generate.ts)
import { DateTimeFormatter, Locale } from "../../../sdk/index.ts";
import { ChapterMode, MadaraNoAjax } from "../../../themes/madara/index.ts";

export default class ZinmangaNet extends MadaraNoAjax {
  override chapterDateFormat = DateTimeFormatter.ofPattern("MM/dd/yyyy", Locale.ROOT);

  override chapterMode = ChapterMode.MangaAjax;

  override filterNonMangaItems = false;
}
