// Generated by tools/messages.ts from upstream hiper/assets/i18n. Do not edit.
import type { Messages } from "../../sdk/i18n.ts";

export const messages: Messages = {
  "en": {
    "genre_filter_title": "Genres",
    "type_filter_title": "Type",
    "rating_filter_title": "Rating",
    "status_filter_title": "Status",
    "status_all": "All",
    "status_ongoing": "Ongoing",
    "status_onhiatus": "Hiatus",
    "status_completed": "Completed",
    "status_canceled": "Canceled",
    "sort_by_filter_title": "Sort By",
    "sort_by_relevance": "Relevance",
    "sort_by_popular": "Popularity",
    "sort_by_score": "Score",
    "sort_by_recent": "Recent Updated",
    "sort_by_newest": "Newest",
    "sort_by_oldest": "Oldest",
    "pref_rating_title": "Default max rating",
    "pref_rating_summary": "Restricts content to the selected rating or below.\nCurrently:"
  },
  "pt-BR": {
    "genre_filter_title": "Gêneros",
    "type_filter_title": "Tipo",
    "rating_filter_title": "Classificação",
    "status_filter_title": "Estado",
    "status_all": "Todos",
    "status_ongoing": "Em andamento",
    "status_onhiatus": "Hiato",
    "status_completed": "Completo",
    "status_canceled": "Cancelado",
    "sort_by_filter_title": "Ordenar por",
    "sort_by_relevance": "Relevância",
    "sort_by_popular": "Popularidade",
    "sort_by_score": "Nota",
    "sort_by_recent": "Atualizados recentemente",
    "sort_by_newest": "Mais recentes",
    "sort_by_oldest": "Mais antigos",
    "pref_rating_title": "Classificação máxima padrão",
    "pref_rating_summary": "Restringe o conteúdo à classificação selecionada ou inferior.\nAtualmente:"
  }
};
