// Port of keiyoushi/extensions-source src/all/comicsvalley/ComicsValley.kt (generated by tools/generate.ts)
import { DateTimeFormatter, Locale } from "../../../sdk/index.ts";
import { ChapterMode, Madara } from "../../../themes/madara/index.ts";

export default class ComicsValley extends Madara {
  override mangaSubString = "comics-new";

  override chapterMode = ChapterMode.MangaAjax;

  override chapterDateFormat = DateTimeFormatter.ofPattern("dd/MM/yyyy", Locale.ROOT);
}
