// Port of keiyoushi/extensions-source src/en/wearehunger/Wearehunger.kt (generated by tools/generate.ts)
import { ChapterMode, Madara } from "../../../themes/madara/index.ts";

export default class Wearehunger extends Madara {
  override chapterMode = ChapterMode.MangaAjax;
}
