// Port of keiyoushi/extensions-source src/en/toongod/ToonGod.kt (generated by tools/generate.ts)
import { DateTimeFormatter, Locale } from "../../../sdk/index.ts";
import { MadaraNoAjax } from "../../../themes/madara/index.ts";

export default class ToonGod extends MadaraNoAjax {
  override chapterDateFormat = DateTimeFormatter.ofPattern("d MMM yyyy", Locale.US);

  override mangaSubString = "webtoons";
}
