// Port of keiyoushi/extensions-source src/en/manga18x/Manga18x.kt (generated by tools/generate.ts)
import { ChapterMode, Madara } from "../../../themes/madara/index.ts";

export default class Manga18x extends Madara {
  override chapterMode = ChapterMode.MangaAjax;
}
