// Port of keiyoushi/extensions-source src/id/komikdewasa/KomikDewasa.kt (generated by tools/generate.ts)
import { ClientBuilder } from "../../../sdk/index.ts";
import { MangaThemesia } from "../../../themes/mangathemesia/index.ts";

export default class KomikDewasa extends MangaThemesia {
  override mangaUrlDirectory = "/komik";

  override datePattern = "d MMMM yyyy";

  override hasProjectPage = true;

  protected override configureClient(b: ClientBuilder) {
    b.addInterceptor(this.acceptHeaderInterceptor());
    return b;
  }
}
