// Port of keiyoushi/extensions-source src/en/galaxymanga/GalaxyManga.kt (generated by tools/generate.ts)
import { MangaThemesia } from "../../../themes/mangathemesia/index.ts";

export default class GalaxyManga extends MangaThemesia {}
