// Port of keiyoushi/extensions-source src/id/dailysuka/DailySuka.kt (generated by tools/generate.ts)
import { MangaThemesia } from "../../../themes/mangathemesia/index.ts";

export default class DailySuka extends MangaThemesia {
  override mangaUrlDirectory = "/komik";
}
