// Port of keiyoushi/extensions-source src/en/manhuahot/ManhuaHot.kt (generated by tools/generate.ts)
import { Madara } from "../../../themes/madara/index.ts";

export default class ManhuaHot extends Madara {}
