// Port of keiyoushi/extensions-source src/en/tritiniascans/TritiniaScans.kt (generated by tools/generate.ts)
import { ChapterMode, Madara } from "../../../themes/madara/index.ts";

export default class TritiniaScans extends Madara {
  override chapterMode = ChapterMode.MangaAjax;
}
