// Port of keiyoushi/extensions-source src/en/boratscans/BoratScans.kt (generated by tools/generate.ts)
import { ChapterMode, Madara } from "../../../themes/madara/index.ts";

export default class BoratScans extends Madara {
  override chapterMode = ChapterMode.MangaAjax;
}
