// Port of keiyoushi/extensions-source src/all/allporncomicsco/AllPornComicsCo.kt (generated by tools/generate.ts)
import { DateTimeFormatter, Locale } from "../../../sdk/index.ts";
import { MadaraNoAjax } from "../../../themes/madara/index.ts";

export default class AllPornComicsCo extends MadaraNoAjax {
  override chapterDateFormat = DateTimeFormatter.ofPattern("dd/MM/yyyy", Locale.ROOT);

  override mangaSubString = "comic";

  override archiveUrlSelector = "h3 > a:not([target=_self]):last-of-type";
}
