// Port of keiyoushi/extensions-source src/en/topmanhuanet/TopManhuaNet.kt (generated by tools/generate.ts)
import { ChapterMode, Madara } from "../../../themes/madara/index.ts";

export default class TopManhuaNet extends Madara {
  override chapterMode = ChapterMode.MangaAjax;
}
