// Port of keiyoushi/extensions-source src/en/webtoonscan/WebtoonScan.kt (generated by tools/generate.ts)
import { Madara } from "../../../themes/madara/index.ts";

export default class WebtoonScan extends Madara {}
