// Port of keiyoushi/extensions-source src/en/lagoonscans/LagoonScans.kt (generated by tools/generate.ts)
import { MangaThemesia } from "../../../themes/mangathemesia/index.ts";

export default class LagoonScans extends MangaThemesia {}
