// Port of keiyoushi/extensions-source src/en/milftoon/Milftoon.kt (generated by tools/generate.ts)
import { MadaraNoAjax } from "../../../themes/madara/index.ts";

export default class Milftoon extends MadaraNoAjax {
  override mangaSubString = "comics";
}
