// Port of keiyoushi/extensions-source src/en/hadesscans/HadesScans.kt (generated by tools/generate.ts)
import { MangaThemesia } from "../../../themes/mangathemesia/index.ts";

export default class HadesScans extends MangaThemesia {}
