// Port of keiyoushi/extensions-source src/id/kumopoi/Filters.kt
import { Filter } from "../../../sdk/index.ts";

const sortOptions: [string, string][] = [
  ["Terbaru", "latest"],
  ["Terpopuler", "popular"],
  ["A - Z", "az"],
  ["Z - A", "za"],
];
export class SortFilter extends Filter.Select<string> {
  constructor(defaultValue = "latest") {
    super(
      "Urutan",
      sortOptions.map((it) => it[0]),
      Math.max(
        sortOptions.findIndex((it) => it[1] === defaultValue),
        0,
      ),
    );
  }
  get selected() {
    return sortOptions[this.state][1];
  }
}

const typeOptions: [string, string][] = [
  ["Semua", ""],
  ["Manhwa (Korea)", "MANHWA"],
  ["Manga (Jepang)", "MANGA"],
  ["Manhua (China)", "MANHUA"],
];
export class TypeFilter extends Filter.Select<string> {
  constructor() {
    super(
      "Tipe",
      typeOptions.map((it) => it[0]),
    );
  }
  get selected() {
    return typeOptions[this.state][1];
  }
}

const statusOptions: [string, string][] = [
  ["Semua", ""],
  ["Ongoing", "ONGOING"],
  ["Completed", "END"],
];
export class StatusFilter extends Filter.Select<string> {
  constructor() {
    super(
      "Status",
      statusOptions.map((it) => it[0]),
    );
  }
  get selected() {
    return statusOptions[this.state][1];
  }
}

export class Genre extends Filter.CheckBox {
  constructor(
    name: string,
    readonly slug: string,
  ) {
    super(name);
  }
}

export class GenreFilter extends Filter.Group<Genre> {
  constructor(genres: Genre[] = getGenres()) {
    super("Genre", genres);
  }
}

export const getGenres = (): Genre[] => GENRES.map(([name, slug]) => new Genre(name, slug));
const GENRES: [string, string][] = [
  ["Action", "action"],
  ["Adult", "adult"],
  ["Adventure", "adventure"],
  ["Age Regression", "age-regression"],
  ["Ahegao", "ahegao"],
  ["Amputee", "amputee"],
  ["Anal", "anal"],
  ["Apron", "apron"],
  ["Artist CG", "artist-cg"],
  ["Aunt", "aunt"],
  ["Bald", "bald"],
  ["BDSM", "bdsm"],
  ["Beauty Mark", "beauty-mark"],
  ["Bestiality", "bestiality"],
  ["Big Areolae", "big-areolae"],
  ["Big Ass", "big-ass"],
  ["Big Breast", "big-breast"],
  ["Big Nipples", "big-nipples"],
  ["Big Penis", "big-penis"],
  ["Bike Shorts", "bike-shorts"],
  ["Bikini", "bikini"],
  ["Birth", "birth"],
  ["Bisexual", "bisexual"],
  ["Biting", "biting"],
  ["Blackmail", "blackmail"],
  ["Blindfold", "blindfold"],
  ["Bloomers", "bloomers"],
  ["Blowjob", "blowjob"],
  ["Body Swap", "body-swap"],
  ["Bodysuit", "bodysuit"],
  ["Bondage", "bondage"],
  ["Booty", "booty"],
  ["Bride", "bride"],
  ["Bukkake", "bukkake"],
  ["Bullying", "bullying"],
  ["Bunny Girl", "bunny-girl"],
  ["Business Suit", "business-suit"],
  ["Busty", "busty"],
  ["Censored", "censored"],
  ["Cheating", "cheating"],
  ["Cohabitation", "cohabitation"],
  ["Collar", "collar"],
  ["Comedy", "comedy"],
  ["Condom", "condom"],
  ["Cosplay", "cosplay"],
  ["Cousin", "cousin"],
  ["Cowgirl", "cowgirl"],
  ["Creampie", "creampie"],
  ["Crossdressing", "crossdressing"],
  ["Cunnilingus", "cunnilingus"],
  ["Dark Skin", "dark-skin"],
  ["Daughter", "daughter"],
  ["Deepthroat", "deepthroat"],
  ["Defloration", "defloration"],
  ["Demon", "demon"],
  ["Demon Girl", "demon-girl"],
  ["Dick Growth", "dick-growth"],
  ["Digital", "digital"],
  ["DILF", "dilf"],
  ["Double Penetration", "double-penetration"],
  ["Doujin", "doujin"],
  ["Drama", "drama"],
  ["Drugs", "drugs"],
  ["Drunk", "drunk"],
  ["Ecchi", "ecchi"],
  ["Elf", "elf"],
  ["Emotionless Sex", "emotionless-sex"],
  ["Exhibitionism", "exhibitionism"],
  ["Eyepatch", "eyepatch"],
  ["Fantasy", "fantasy"],
  ["Females Only", "females-only"],
  ["Femdom", "femdom"],
  ["Filming", "filming"],
  ["Fingering", "fingering"],
  ["Footjob", "footjob"],
  ["Fuck Piercing", "fuck-piercing"],
  ["Full Color", "full-color"],
  ["Furry", "furry"],
  ["Futanari", "futanari"],
  ["Garter Belt", "garter-belt"],
  ["Gender Bender", "gender-bender"],
  ["Ghost", "ghost"],
  ["Glasses", "glasses"],
  ["Gloves", "gloves"],
  ["Gokkun", "gokkun"],
  ["Group", "group"],
  ["Growth", "growth"],
  ["Guro", "guro"],
  ["Gyaru", "gyaru"],
  ["Hairy", "hairy"],
  ["Handjob", "handjob"],
  ["Harem", "harem"],
  ["Hidden Sex", "hidden-sex"],
  ["Historical", "historical"],
  ["Horns", "horns"],
  ["Horror", "horror"],
  ["Huge Breast", "huge-breast"],
  ["Humiliation", "humiliation"],
  ["Impregnation", "impregnation"],
  ["Incest", "incest"],
  ["Inflation", "inflation"],
  ["Insect", "insect"],
  ["Inseki", "inseki"],
  ["Inverted Nipples", "inverted-nipples"],
  ["Invisible", "invisible"],
  ["Isekai", "isekai"],
  ["Josei", "josei"],
  ["Kemomimi", "kemomimi"],
  ["Kimono", "kimono"],
  ["Kissing", "kissing"],
  ["Kuudere", "kuudere"],
  ["Lactation", "lactation"],
  ["Leotard", "leotard"],
  ["Lingerie", "lingerie"],
  ["Loli", "loli"],
  ["Lolipai", "lolipai"],
  ["Long Strip", "long-strip"],
  ["Maid", "maid"],
  ["Males Only", "males-only"],
  ["Martial Arts", "martial-arts"],
  ["Massage", "massage"],
  ["Masturbation", "masturbation"],
  ["Mating Press", "mating-press"],
  ["Mature", "mature"],
  ["Miko", "miko"],
  ["MILF", "milf"],
  ["Mind Break", "mind-break"],
  ["Mind Control", "mind-control"],
  ["Monster", "monster"],
  ["Monster Girl", "monster-girl"],
  ["Monsters", "monsters"],
  ["Mother", "mother"],
  ["Multi-work Series", "multi-work-series"],
  ["Muscle", "muscle"],
  ["Mystery", "mystery"],
  ["Nakadashi", "nakadashi"],
  ["Netorare", "netorare"],
  ["Netorase", "netorase"],
  ["Netori", "netori"],
  ["Niece", "niece"],
  ["Nipple", "nipple"],
  ["Nipple Fuck", "nipple-fuck"],
  ["Nipples", "nipples"],
  ["No Penetration", "no-penetration"],
  ["Nurse", "nurse"],
  ["Old Man", "old-man"],
  ["Original", "original"],
  ["Osananajimi", "osananajimi"],
  ["Oyakodon", "oyakodon"],
  ["Paizuri", "paizuri"],
  ["Pantyhose", "pantyhose"],
  ["Piercing", "piercing"],
  ["Ponytail", "ponytail"],
  ["Possession", "possession"],
  ["Pregnant", "pregnant"],
  ["Prostitution", "prostitution"],
  ["Psychological", "psychological"],
  ["Pupils", "pupils"],
  ["Rape", "rape"],
  ["Regression", "regression"],
  ["Rimjob", "rimjob"],
  ["Romance", "romance"],
  ["Scat", "scat"],
  ["School Life", "school-life"],
  ["School Uniform", "school-uniform"],
  ["Sci-Fi", "sci-fi"],
  ["Seinen", "seinen"],
  ["Sex toys", "sex-toys"],
  ["Shemale", "shemale"],
  ["Shibari", "shibari"],
  ["Shota", "shota"],
  ["Shoujo", "shoujo"],
  ["Shounen", "shounen"],
  ["Sister", "sister"],
  ["Sleeping", "sleeping"],
  ["Slice of Life", "slice-of-life"],
  ["Slime", "slime"],
  ["Small Breast", "small-breast"],
  ["Small Penis", "small-penis"],
  ["Smell", "smell"],
  ["Smut", "smut"],
  ["Snuff", "snuff"],
  ["Sole Female", "sole-female"],
  ["Sole Male", "sole-male"],
  ["Sports", "sports"],
  ["Squirting", "squirting"],
  ["Stocking", "stocking"],
  ["Story Arc", "story-arc"],
  ["Sumata", "sumata"],
  ["Supernatural", "supernatural"],
  ["Sweating", "sweating"],
  ["Swimsuit", "swimsuit"],
  ["Swinging", "swinging"],
  ["Tail", "tail"],
  ["Tall girl", "tall-girl"],
  ["Tankoubon", "tankoubon"],
  ["Tanlines", "tanlines"],
  ["Teacher", "teacher"],
  ["Tentacles", "tentacles"],
  ["Threesome", "threesome"],
  ["Tomboy", "tomboy"],
  ["Tomgirl", "tomgirl"],
  ["Torture", "torture"],
  ["Tragedy", "tragedy"],
  ["Tsundere", "tsundere"],
  ["Twins", "twins"],
  ["Twintails", "twintails"],
  ["Ugly Bastard", "ugly-bastard"],
  ["Uncensored", "uncensored"],
  ["Unusual Pupils", "unusual-pupils"],
  ["Vanilla", "vanilla"],
  ["Virginity", "virginity"],
  ["Voyeurism", "voyeurism"],
  ["Widow", "widow"],
  ["Wings", "wings"],
  ["X-Ray", "x-ray"],
  ["Yandere", "yandere"],
  ["Yaoi", "yaoi"],
  ["Yuri", "yuri"],
];
