// Port of keiyoushi/extensions-source src/en/manhwatoon/ManhwaToon.kt (generated by tools/generate.ts)
import { ChapterMode, Madara } from "../../../themes/madara/index.ts";

export default class ManhwaToon extends Madara {
  override chapterMode = ChapterMode.MangaAjax;

  protected override configureHeaders(h: Headers) {
    h.delete("Origin");
    return h;
  }
}
