// Port of keiyoushi/extensions-source src/en/manhwareads/ManhwaReads.kt (generated by tools/generate.ts)
import { ChapterMode, Madara } from "../../../themes/madara/index.ts";

export default class ManhwaReads extends Madara {
  override chapterMode = ChapterMode.MangaAjax;
}
