// Port of keiyoushi/extensions-source src/id/kuromanga/KuroManga.kt (generated by tools/generate.ts)
import { MangaThemesia } from "../../../themes/mangathemesia/index.ts";

export default class KuroManga extends MangaThemesia {}
