// Port of keiyoushi/extensions-source src/id/dojingnet/DojingNet.kt (generated by tools/generate.ts)
import { ClientBuilder } from "../../../sdk/index.ts";
import { MangaThemesia } from "../../../themes/mangathemesia/index.ts";

export default class DojingNet extends MangaThemesia {
  protected override configureClient(b: ClientBuilder) {
    b.rateLimit(4, 1000);
    return b;
  }

  override hasProjectPage = true;
}
