// Port of keiyoushi/extensions-source src/en/razure/Razure.kt (generated by tools/generate.ts)
import { MangaThemesia } from "../../../themes/mangathemesia/index.ts";

export default class Razure extends MangaThemesia {
  override mangaUrlDirectory = "/series";

  override chapterListSelector() {
    return "#chapterlist li:not([data-num*='🔒'])";
  }

  override searchMangaSelector() {
    return ".listupd .bs .bsx:not(:has(.novelabel))";
  }
}
