// Port of keiyoushi/extensions-source src/en/mangaforfreecom/Mangaforfreecom.kt (generated by tools/generate.ts)
import { ChapterMode, Madara } from "../../../themes/madara/index.ts";

export default class Mangaforfreecom extends Madara {
  override chapterMode = ChapterMode.AdminAjax;
}
