// Port of keiyoushi/extensions-source src/en/galaxydegenscans/GalaxyDegenScans.kt (generated by tools/generate.ts)
import { ChapterMode, Madara } from "../../../themes/madara/index.ts";

export default class GalaxyDegenScans extends Madara {
  override chapterMode = ChapterMode.MangaAjax;
}
