// Port of keiyoushi/extensions-source src/en/allporncomic/AllPornComic.kt (generated by tools/generate.ts)
import { MadaraNoAjax } from "../../../themes/madara/index.ts";

export default class AllPornComic extends MadaraNoAjax {
  override mangaSubString = "porncomic";
}
