// Port of keiyoushi/extensions-source src/en/manhwaden/ManhwaDen.kt (generated by tools/generate.ts)
import { ChapterMode, MadaraNoAjax } from "../../../themes/madara/index.ts";

export default class ManhwaDen extends MadaraNoAjax {
  override chapterMode = ChapterMode.MangaAjax;

  override filterNonMangaItems = false;
}
