// Port of keiyoushi/extensions-source src/id/manhwalistid/ManhwaList.kt (generated by tools/generate.ts)
import { ClientBuilder } from "../../../sdk/index.ts";
import { MangaThemesia } from "../../../themes/mangathemesia/index.ts";

export default class ManhwaList extends MangaThemesia {
  protected override configureClient(b: ClientBuilder) {
    b.rateLimit(3, 1000);
    return b;
  }
}
