// Port of keiyoushi/extensions-source src/en/petrotechsociety/Petrotechsociety.kt (generated by tools/generate.ts)
import { DateTimeFormatter } from "../../../sdk/index.ts";
import { Madara } from "../../../themes/madara/index.ts";

export default class Petrotechsociety extends Madara {
  override chapterDateFormat = DateTimeFormatter.ofPattern("dd/MM/yyyy");
}
