// Port of keiyoushi/extensions-source src/en/jinmangas/Jinmangas.kt (generated by tools/generate.ts)
import { ChapterMode, Madara } from "../../../themes/madara/index.ts";

export default class Jinmangas extends Madara {
  override chapterMode = ChapterMode.MangaAjax;
}
