// Port of keiyoushi/extensions-source src/en/gourmetscans/GourmetScans.kt (generated by tools/generate.ts)
import { Madara } from "../../../themes/madara/index.ts";

export default class GourmetScans extends Madara {
  override mangaSubString = "project";

  override genreDirectory = "genre";

  override ajaxTemplate = "wp-manga/content/content-archive";
}
