// Port of keiyoushi/extensions-source lib-multisrc/mangabox/Filters.kt
import { Filter } from "../../sdk/index.ts";

export class UriPartFilter extends Filter.Select<string> {
  constructor(
    displayName: string,
    private readonly vals: [string | null, string][],
  ) {
    super(
      displayName,
      vals.map((it) => it[1]),
    );
  }
  toUriPart() {
    return this.vals[this.state][0];
  }
}

export class SortFilter extends UriPartFilter {
  constructor(vals: [string | null, string][]) {
    super("Order by", vals);
  }
}
export class StatusFilter extends UriPartFilter {
  constructor(vals: [string | null, string][]) {
    super("Status", vals);
  }
}
export class GenreFilter extends UriPartFilter {
  constructor(vals: [string | null, string][]) {
    super("Category", vals);
  }
}

export const getSortFilters = (): [string | null, string][] => [
  ["latest", "Latest"],
  ["newest", "Newest"],
  ["topview", "Top read"],
];

export const getStatusFilters = (): [string | null, string][] => [
  ["all", "ALL"],
  ["completed", "Completed"],
  ["ongoing", "Ongoing"],
];

export const getGenreFilters = (): [string | null, string][] => [
  ["all", "ALL"],
  ["4-koma", "4-Koma"],
  ["action", "Action"],
  ["adaptation", "Adaptation"],
  ["adult", "Adult"],
  ["adventure", "Adventure"],
  ["age-gap", "Age gap"],
  ["ai-art", "Ai art"],
  ["aliens", "Aliens"],
  ["animals", "Animals"],
  ["anthology", "Anthology"],
  ["artbook", "Artbook"],
  ["avant-garde", "Avant garde"],
  ["award-winning", "Award winning"],
  ["beasts", "Beasts"],
  ["boys-love", "Boys love"],
  ["blackmail", "Blackmail"],
  ["bloody", "Bloody"],
  ["bodyswap", "Bodyswap"],
  ["brocon-siscon", "Brocon/Siscon"],
  ["cars", "Cars"],
  ["cartoon", "Cartoon"],
  ["cheating-infidelity", "Cheating infidelity"],
  ["childhood-friends", "Childhood friends"],
  ["college-life", "College life"],
  ["comedy", "Comedy"],
  ["comic", "Comic"],
  ["contest-winning", "Contest winning"],
  ["cooking", "Cooking"],
  ["creators", "Creators"],
  ["crime", "Crime"],
  ["crossdressing", "Crossdressing"],
  ["cultivation", "Cultivation"],
  ["death-game", "Death game"],
  ["degeneratemc", "Degeneratemc"],
  ["delinquents", "Delinquents"],
  ["dementia", "Dementia"],
  ["demons", "Demons"],
  ["doujinshi", "Doujinshi"],
  ["drama", "Drama"],
  ["ecchi", "Ecchi"],
  ["employee", "Employee"],
  ["erotica", "Erotica"],
  ["fan-colored", "Fan colored"],
  ["fantasy", "Fantasy"],
  ["female-protagonists", "Female protagonists"],
  ["fetish", "Fetish"],
  ["full-color", "Full color"],
  ["game", "Game"],
  ["gender-bender", "Gender bender"],
  ["genderswap", "Genderswap"],
  ["ghosts", "Ghosts"],
  ["girls-love", "Girls love"],
  ["gore", "Gore"],
  ["gourmet", "Gourmet"],
  ["graphic-novel", "Graphic novel"],
  ["gyaru", "Gyaru"],
  ["harem", "Harem"],
  ["heartwarming", "Heartwarming"],
  ["hentai", "Hentai"],
  ["historical", "Historical"],
  ["horror", "Horror"],
  ["imageset", "Imageset"],
  ["incest", "Incest"],
  ["informative", "Informative"],
  ["isekai", "Isekai"],
  ["iyashikei", "Iyashikei"],
  ["josei", "Josei"],
  ["kids", "Kids"],
  ["korean", "Korean"],
  ["liexing", "Liexing"],
  ["loli", "Loli"],
  ["long-strip", "Long strip"],
  ["mafia", "Mafia"],
  ["magic", "Magic"],
  ["magical-girls", "Magical girls"],
  ["mahou-shoujo", "Mahou shoujo"],
  ["male-protagonists", "Male protagonists"],
  ["manga", "Manga"],
  ["mangatoon", "Mangatoon"],
  ["manhua", "Manhua"],
  ["manhwa", "Manhwa"],
  ["martial-arts", "Martial arts"],
  ["master-servant", "Master servant"],
  ["mature", "Mature"],
  ["mecha", "Mecha"],
  ["medical", "Medical"],
  ["military", "Military"],
  ["monsters", "Monsters"],
  ["monster-girls", "Monster girls"],
  ["murim", "Murim"],
  ["music", "Music"],
  ["mystery", "Mystery"],
  ["netorare", "Netorare"],
  ["netori", "Netori"],
  ["ninja", "Ninja"],
  ["non-human", "Non human"],
  ["office", "Office"],
  ["office-workers", "Office workers"],
  ["official-colored", "Official colored"],
  ["old-people", "Old people"],
  ["omegaverse", "Omegaverse"],
  ["one-shot", "One shot"],
  ["others", "Others"],
  ["overpowered", "Overpowered"],
  ["parody", "Parody"],
  ["philosophical", "Philosophical"],
  ["ping-ping-jun", "Ping ping jun"],
  ["police", "Police"],
  ["pornographic", "Pornographic"],
  ["post-apocalyptic", "Post apocalyptic"],
  ["psychological", "Psychological"],
  ["reincarnation", "Reincarnation"],
  ["revenge", "Revenge"],
  ["reverse", "Reverse"],
  ["reverse-harem", "Reverse harem"],
  ["romance", "Romance"],
  ["royal-family", "Royal family"],
  ["royalty", "Royalty"],
  ["samurai", "Samurai"],
  ["school", "School"],
  ["school-life", "School life"],
  ["sci-fi", "Sci fi"],
  ["science-fiction", "Science fiction"],
  ["seinen", "Seinen"],
  ["self-published", "Self published"],
  ["sexual-violence", "Sexual violence"],
  ["shota", "Shota"],
  ["shoujo", "Shoujo"],
  ["shoujo-ai", "Shoujo ai"],
  ["shounen", "Shounen"],
  ["shounen-ai", "Shounen ai"],
  ["showbiz", "Showbiz"],
  ["slice-of-life", "Slice of life"],
  ["smut", "Smut"],
  ["sm-bdsm", "Sm bdsm"],
  ["soft-yaoi", "Soft yaoi"],
  ["space", "Space"],
  ["sports", "Sports"],
  ["spy", "Spy"],
  ["step-family", "Step family"],
  ["super-power", "Super power"],
  ["superhero", "Superhero"],
  ["supernatural", "Supernatural"],
  ["survival", "Survival"],
  ["suspense", "Suspense"],
  ["system", "System"],
  ["teacher-student", "Teacher student"],
  ["thriller", "Thriller"],
  ["time-travel", "Time travel"],
  ["traditional-games", "Traditional games"],
  ["tragedy", "Tragedy"],
  ["vampires", "Vampires"],
  ["video-games", "Video games"],
  ["villainess", "Villainess"],
  ["violence", "Violence"],
  ["virtual-reality", "Virtual reality"],
  ["web-comic", "Web comic"],
  ["webtoons", "Webtoons"],
  ["western", "Western"],
  ["wuxia", "Wuxia"],
  ["xianxia", "Xianxia"],
  ["yaoi", "Yaoi"],
  ["yuri", "Yuri"],
  ["zombies", "Zombies"],
];
