// Port of keiyoushi/extensions-source src/en/paritehaber/Paritehaber.kt (generated by tools/generate.ts)
import { Madara } from "../../../themes/madara/index.ts";

export default class Paritehaber extends Madara {}
