// Port of keiyoushi/extensions-source src/en/manhwaget/ManhwaGet.kt (generated by tools/generate.ts)
import { ChapterMode, Madara } from "../../../themes/madara/index.ts";

export default class ManhwaGet extends Madara {
  override chapterMode = ChapterMode.MangaAjax;
}
