// Turn an upstream assets/i18n folder into a TypeScript messages module:
//   npx tsx tools/messages.ts <upstream assets/i18n dir> <out.ts>
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, relative } from "node:path";
import { parseProperties } from "../sdk/i18n.ts";

const [dir, out] = process.argv.slice(2);
const messages: Record<string, Record<string, string>> = {};
for (const f of readdirSync(dir).sort()) {
  const m = /^messages_(.+)\.properties$/.exec(f);
  if (!m) continue;
  // messages_pt_br -> pt-BR, as Intl's createDefaultMessageFileName inverts it
  const tag = m[1].replace(/_(\w+)$/, (_, c: string) => `-${c.toUpperCase()}`);
  messages[tag] = parseProperties(readFileSync(`${dir}/${f}`, "utf8"));
}
writeFileSync(out, `// Generated by tools/messages.ts from upstream ${dir.split("/").slice(-3).join("/")}. Do not edit.\nimport type { Messages } from "${relative(dirname(out), "sdk/i18n.ts")}";\n\nexport const messages: Messages = ${JSON.stringify(messages, null, 2)};\n`);
console.log(`${out}: ${Object.keys(messages).join(", ")} (${Object.keys(messages.en ?? {}).length} keys)`);
