// Translate a themed extension's Kotlin into a TypeScript port - but only when every member is a pattern understood
// here: property overrides, one-line selector functions, rate limits, interceptors and header tweaks. Anything else
// returns the reason, and that extension is ported by hand. A partial translation is never written.

export type Translation = { ok: true; code: string } | { ok: false; reason: string };

const THEMES: Record<string, { theme: string; getters: string[] }> = {
  Madara: { theme: "madara", getters: ["xhrHeaders"] },
  MadaraNoAjax: { theme: "madara", getters: ["xhrHeaders"] },
  MangaThemesia: { theme: "mangathemesia", getters: ["dateFormat", "popularFilter", "latestFilter"] },
  MangaThemesiaAlt: { theme: "mangathemesia", getters: ["dateFormat", "popularFilter", "latestFilter", "listUrl"] },
};
const SOURCE_GETTERS = ["supportsLatest", "supportsRelatedMangas", "supportsFilterFetching"];
const THIS_FIELDS = new Set(["baseUrl", "name", "lang", "mangaSubString", "mangaUrlDirectory", "id"]);
export const GENERATED = "generated by tools/generate.ts";

class Unsupported extends Error {}
const fail = (why: string): never => {
  throw new Unsupported(why);
};

/** Drop comments without touching "//" inside strings (URLs). */
function stripComments(src: string): string {
  let out = "";
  for (let i = 0; i < src.length; ) {
    if (src.startsWith('"""', i)) {
      const end = src.indexOf('"""', i + 3);
      out += src.slice(i, end + 3);
      i = end + 3;
    } else if (src[i] === '"') {
      let j = i + 1;
      while (j < src.length && src[j] !== '"') j += src[j] === "\\" ? 2 : 1;
      out += src.slice(i, j + 1);
      i = j + 1;
    } else if (src.startsWith("//", i)) i = src.indexOf("\n", i) < 0 ? src.length : src.indexOf("\n", i);
    else if (src.startsWith("/*", i)) i = src.indexOf("*/", i) + 2;
    else out += src[i++];
  }
  return out;
}

/** Index just past the brace that closes the one at `open`, skipping strings. */
function matchBrace(src: string, open: number): number {
  let depth = 0;
  for (let i = open; i < src.length; i++) {
    const c = src[i];
    if (c === '"') {
      if (src.startsWith('"""', i)) i = src.indexOf('"""', i + 3) + 2;
      else for (i++; i < src.length && src[i] !== '"'; i += src[i] === "\\" ? 2 : 1);
    } else if (c === "{" || c === "(") depth++;
    else if (c === "}" || c === ")") {
      if (--depth === 0) return i + 1;
    }
  }
  return fail("unbalanced braces");
}

/** Split a class body into its top-level members. */
function members(body: string): string[] {
  const out: string[] = [];
  let start = -1;
  let depth = 0;
  const starts = /^(?:@\w+\s+)*(?:override|private|protected|public|internal|open|val|var|fun|init|companion|object|class|data|enum|lateinit|const)\b/;
  for (let i = 0; i < body.length; i++) {
    const c = body[i];
    if (c === '"') {
      if (body.startsWith('"""', i)) i = body.indexOf('"""', i + 3) + 2;
      else for (i++; i < body.length && body[i] !== '"'; i += body[i] === "\\" ? 2 : 1);
      continue;
    }
    if (c === "{" || c === "(" || c === "[") depth++;
    else if (c === "}" || c === ")" || c === "]") depth--;
    else if (depth === 0 && (i === 0 || body[i - 1] === "\n") ) {
      const line = body.slice(i).trimStart();
      if (starts.test(line) && body.slice(i, i + (body.slice(i).length - line.length)).trim() === "") {
        if (start >= 0) out.push(body.slice(start, i).trim());
        start = i;
      }
    }
  }
  if (start >= 0) out.push(body.slice(start).trim());
  return out.filter(Boolean);
}

// --- expressions -------------------------------------------------------------------------

/** A Kotlin string literal (regular with escapes and $templates, or raw) -> a JS expression. */
function kstring(lit: string): string {
  let raw: string;
  if (lit.startsWith('"""')) raw = lit.slice(3, -3);
  else {
    raw = "";
    const body = lit.slice(1, -1);
    for (let i = 0; i < body.length; i++) {
      if (body[i] !== "\\") raw += body[i];
      else {
        const n = body[++i];
        raw += n === "n" ? "\n" : n === "t" ? "\t" : n === "$" ? "\u0000DOLLAR" : n;
      }
    }
  }
  const parts: string[] = [];
  let hasTemplate = false;
  const re = /\$\{(\w+)\}|\$(\w+)/g;
  let last = 0;
  for (let m; (m = re.exec(raw)); ) {
    const id = m[1] ?? m[2];
    if (!THIS_FIELDS.has(id)) fail(`string template $${id}`);
    parts.push(raw.slice(last, m.index).replaceAll("`", "\\`"), `\${this.${id}}`);
    last = re.lastIndex;
    hasTemplate = true;
  }
  parts.push(raw.slice(last).replaceAll("`", "\\`"));
  const text = parts.join("").replaceAll("\u0000DOLLAR", "$");
  return hasTemplate ? "`" + text.replace(/\\(?![`$])/g, "\\\\") + "`" : JSON.stringify(raw.replaceAll("\u0000DOLLAR", "$"));
}

const STRING = String.raw`("""[\s\S]*?"""|"(?:\\.|[^"\\])*")`;
const LOCALE_CONST = new Set(["US", "ENGLISH", "ROOT", "UK", "FRENCH", "GERMAN", "JAPANESE"]);

function locale(expr: string, use: Set<string>): string {
  expr = expr.trim();
  let m: RegExpExecArray | null;
  if ((m = /^Locale\.(\w+)$/.exec(expr))) {
    if (!LOCALE_CONST.has(m[1])) fail(`Locale.${m[1]}`);
    use.add("Locale");
    return `Locale.${m[1]}`;
  }
  if ((m = new RegExp(`^Locale\\.forLanguageTag\\(${STRING}\\)$`).exec(expr))) return use.add("Locale"), `Locale.forLanguageTag(${kstring(m[1])})`;
  if ((m = new RegExp(`^Locale\\(${STRING}(?:\\s*,\\s*${STRING})?\\)$`).exec(expr))) return use.add("Locale"), `new Locale(${kstring(m[1])}${m[2] ? `, ${kstring(m[2])}` : ""})`;
  return fail(`locale ${expr}`);
}

function duration(expr: string): number {
  const m = /^(\d+)(?:L)?\.(milliseconds|seconds|minutes)$/.exec(expr.trim());
  if (!m) return fail(`duration ${expr}`);
  return Number(m[1]) * { milliseconds: 1, seconds: 1000, minutes: 60_000 }[m[2] as "seconds"];
}

/** A value expression for a property override. */
function value(expr: string, use: Set<string>): string {
  expr = expr.trim();
  let m: RegExpExecArray | null;
  if (new RegExp(`^${STRING}$`).test(expr)) return kstring(expr);
  if (/^(true|false|-?\d+(?:\.\d+)?)[LF]?$/.test(expr)) return expr.replace(/[LF]$/, "");
  if ((m = /^ChapterMode\.(\w+)$/.exec(expr))) return use.add("theme:ChapterMode"), `ChapterMode.${m[1]}`;
  if ((m = new RegExp(`^DateTimeFormatter\\.ofPattern\\(${STRING}(?:\\s*,\\s*(.+))?\\)$`).exec(expr))) {
    use.add("DateTimeFormatter");
    return `DateTimeFormatter.ofPattern(${kstring(m[1])}${m[2] ? `, ${locale(m[2], use)}` : ""})`;
  }
  if ((m = new RegExp(`^Regex\\(${STRING}(?:\\s*,\\s*RegexOption\\.IGNORE_CASE)?\\)$`).exec(expr)) || (m = new RegExp(`^${STRING}\\.toRegex\\((?:RegexOption\\.IGNORE_CASE)?\\)$`).exec(expr))) {
    const src = JSON.parse(kstring(m[1]).startsWith("`") ? fail("template in regex") : kstring(m[1])) as string;
    return `new RegExp(${JSON.stringify(src)}${/IGNORE_CASE/.test(expr) ? ', "i"' : ""})`;
  }
  return fail(`value ${expr.slice(0, 60)}`);
}

/** `{ !it.encodedPath.startsWith("/wp-content/uploads/") }` -> `(it) => !it.pathname.startsWith("/wp-content/uploads/")` */
function urlLambda(body: string): string {
  let js = body.trim().replace(/^\{/, "").replace(/\}$/, "").trim();
  if (/\bit\b/.test(js) === false) fail("lambda without it");
  js = js.replace(/\bit\.encodedPath\b/g, "it.pathname").replace(/\bit\.host\b/g, "it.hostname").replace(/\.contains\(/g, ".includes(").replace(/([^=!])==([^=])/g, "$1===$2").replace(/!=([^=])/g, "!==$1");
  const stripped = js.replace(new RegExp(STRING, "g"), '""');
  if (/[^\w\s.!&|()"=<>]/.test(stripped) || /\b(?!it\b|pathname\b|hostname\b|startsWith\b|endsWith\b|includes\b)[A-Za-z_]\w*\b/.test(stripped.replace(/\.\w+/g, (s) => (/^\.(pathname|hostname|startsWith|endsWith|includes)$/.test(s) ? s : "."))))
    fail(`lambda ${body.trim().slice(0, 60)}`);
  js = js.replace(new RegExp(STRING, "g"), (s) => kstring(s));
  return `(it: URL) => ${js}`;
}

/** Split `a(x), b(y)` style argument lists at top-level commas. */
function args(s: string): string[] {
  const out: string[] = [];
  let depth = 0;
  let cur = "";
  for (let i = 0; i < s.length; i++) {
    const c = s[i];
    if (c === '"') {
      const end = s.startsWith('"""', i) ? s.indexOf('"""', i + 3) + 3 : (() => {
        let j = i + 1;
        while (j < s.length && s[j] !== '"') j += s[j] === "\\" ? 2 : 1;
        return j + 1;
      })();
      cur += s.slice(i, end);
      i = end - 1;
      continue;
    }
    if ("({[".includes(c)) depth++;
    if (")}]".includes(c)) depth--;
    if (c === "," && depth === 0) (out.push(cur.trim()), (cur = ""));
    else cur += c;
  }
  if (cur.trim()) out.push(cur.trim());
  return out;
}

/** The statements of `apply { a; b }` or a single call `a`. */
function statements(expr: string): string[] {
  expr = expr.trim();
  const m = /^apply\s*\{([\s\S]*)\}$/.exec(expr);
  if (!m) return [expr];
  return m[1].split(/\n|;/).map((s) => s.trim()).filter(Boolean);
}

function clientCall(stmt: string, use: Set<string>): string {
  let m: RegExpExecArray | null;
  if ((m = /^rateLimit\(([\s\S]*)\)\s*(\{[\s\S]*\})?$/.exec(stmt))) {
    const a = args(m[1]);
    const lambda = m[2] ?? (a.length && a[a.length - 1].startsWith("{") ? a.pop() : undefined);
    if (!a.length || !/^\d+$/.test(a[0])) fail(`rateLimit(${m[1]})`);
    const period = a[1] ? duration(a[1]) : 1000;
    if (a.length > 2) fail(`rateLimit(${m[1]})`);
    return `b.rateLimit(${a[0]}, ${period}${lambda ? `, ${urlLambda(lambda)}` : ""})`;
  }
  if (/^addInterceptor\(acceptHeaderInterceptor\(\)\)$/.test(stmt)) return "b.addInterceptor(this.acceptHeaderInterceptor())";
  if (/^addInterceptor\(ClientHintsInterceptor\(\)\)$/.test(stmt)) return use.add("theme:clientHintsInterceptor"), "b.addInterceptor(clientHintsInterceptor)";
  if ((m = /^(readTimeout|connectTimeout)\((.+)\)$/.exec(stmt))) return `b.${m[1]}(${duration(m[2])})`;
  return fail(`client ${stmt.slice(0, 60)}`);
}

function headerCall(stmt: string): string {
  let m: RegExpExecArray | null;
  if ((m = new RegExp(`^(set|add|header)\\(${STRING}\\s*,\\s*${STRING}\\)$`).exec(stmt))) return `h.${m[1] === "add" ? "append" : "set"}(${kstring(m[2])}, ${kstring(m[3])})`;
  if ((m = new RegExp(`^(removeAll)\\(${STRING}\\)$`).exec(stmt))) return `h.delete(${kstring(m[2])})`;
  return fail(`header ${stmt.slice(0, 60)}`);
}

// --- members ----------------------------------------------------------------------------

function member(src: string, getters: Set<string>, use: Set<string>): string {
  const one = src.replace(/\s+/g, " ").trim();
  let m: RegExpExecArray | null;
  if ((m = /^override (?:val|var) (\w+)(?:\s*:\s*[\w.<>?, ]+)?\s*(?:get\(\)\s*)?=\s*([\s\S]+)$/.exec(src.trim()))) {
    const [, name, expr] = m;
    const v = value(expr, use);
    return getters.has(name) ? `  override get ${name}() {\n    return ${v};\n  }` : `  override ${name} = ${v};`;
  }
  if ((m = /^override fun (\w+)\(\)(?:\s*:\s*String\??)?\s*=\s*([\s\S]+)$/.exec(src.trim()))) {
    const expr = m[2].trim();
    if (!new RegExp(`^${STRING}$`).test(expr)) fail(`fun ${m[1]} = ${expr.slice(0, 50)}`);
    return `  override ${m[1]}() {\n    return ${kstring(expr)};\n  }`;
  }
  if ((m = /^override fun OkHttpClient\.Builder\.configureClient\(\)(?:\s*:\s*OkHttpClient\.Builder)?\s*=\s*([\s\S]+)$/.exec(src.trim()))) {
    use.add("ClientBuilder");
    const calls = statements(m[1]).map((s) => clientCall(s, use));
    return `  protected override configureClient(b: ClientBuilder) {\n${calls.map((c) => `    ${c};`).join("\n")}\n    return b;\n  }`;
  }
  if ((m = /^override fun Headers\.Builder\.configureHeaders\(\)(?:\s*:\s*Headers\.Builder)?\s*=\s*([\s\S]+)$/.exec(src.trim()))) {
    const calls = statements(m[1]).map(headerCall);
    return `  protected override configureHeaders(h: Headers) {\n${calls.map((c) => `    ${c};`).join("\n")}\n    return h;\n  }`;
  }
  return fail(`member ${one.slice(0, 70)}`);
}

/** `files`: the extension's Kotlin sources; `upstreamPath`: e.g. "src/id/klikmanga" (for the header comment). */
export function translate(files: { name: string; text: string }[], upstreamPath: string): Translation {
  try {
    if (files.length !== 1) fail(`${files.length} Kotlin files`);
    const src = stripComments(files[0].text);
    const cls = /(?:abstract\s+|open\s+)?class\s+(\w+)\s*(?:\(([^)]*)\))?\s*:\s*(\w+)\s*\(([^)]*)\)\s*(?:,\s*[\w.]+\s*)*(\{)?/.exec(src);
    if (!cls) fail("no class extending a theme");
    const [, name, ctor, base, baseArgs, brace] = cls!;
    const info = THEMES[base] ?? fail(`base ${base}`);
    if ((ctor ?? "").trim() || baseArgs.trim()) fail("constructor arguments");
    const use = new Set<string>();
    const getters = new Set([...info.getters, ...SOURCE_GETTERS]);
    let body: string[] = [];
    if (brace) {
      // `class X : Theme() { ... }`
      const open = cls!.index + cls![0].length - 1;
      const end = matchBrace(src, open);
      if (src.slice(end).trim()) fail("code after the class");
      body = members(src.slice(open + 1, end - 1)).map((m) => member(m, getters, use));
    } else if (src.slice(cls!.index + cls![0].length).trim()) fail("code after the class"); // `class X : Theme()` has no overrides

    const sdk = [...use].filter((u) => !u.startsWith("theme:")).sort();
    const theme = [base, ...[...use].filter((u) => u.startsWith("theme:")).map((u) => u.slice(6))].sort();
    const lines = [
      `// Port of keiyoushi/extensions-source ${upstreamPath}/${files[0].name} (${GENERATED})`,
      ...(sdk.length ? [`import { ${sdk.join(", ")} } from "../../../sdk/index.ts";`] : []),
      `import { ${theme.join(", ")} } from "../../../themes/${info.theme}/index.ts";`,
      "",
      `export default class ${name} extends ${base} {`,
      body.join("\n\n"),
      "}",
      "",
    ];
    return { ok: true, code: lines.join("\n").replace(/\{\n\n\}/, "{}") };
  } catch (e) {
    if (e instanceof Unsupported) return { ok: false, reason: e.message };
    throw e;
  }
}
