// Generated by tools/messages.ts from upstream comikey/assets/i18n. Do not edit.
import type { Messages } from "../../../sdk/i18n.ts";

export const messages: Messages = {
  "en": {
    "sort_by": "Sort by",
    "sort_last_updated": "Last updated",
    "sort_name": "Name",
    "sort_popularity": "Popularity",
    "sort_chapter_count": "Chapter count",
    "filter_by": "Filter by",
    "all": "All",
    "manga": "Manga",
    "webtoon": "Webtoon",
    "new": "New",
    "complete": "Complete",
    "exclusive": "Exclusive",
    "simulpub": "Simulpub",
    "search_use_two_characters": "Please use at least 2 characters when searching by title.",
    "pref_hide_locked_chapters": "Hide locked chapters",
    "error_timed_out_decrypting_image_links": "Timed out decrypting image links",
    "error_locked_chapter_unlock_in_webview": "Locked chapter, unlock in WebView.",
    "error_open_in_webview_then_try_again": "Open chapter in WebView, then try again",
    "error_token_expired": "token expired",
    "error_token_not_found": "token not found",
    "error_webview_script_not_found": "WebView script not found.",
    "error_unknown_error": "Unknown error"
  },
  "pt-BR": {
    "sort_by": "Ordenar por",
    "sort_last_updated": "Última atualização",
    "sort_name": "Nome",
    "sort_popularity": "Popularidade",
    "sort_chapter_count": "Capítulos",
    "filter_by": "Filtrar por",
    "all": "Todos",
    "manga": "Manga",
    "webtoon": "Webtoon",
    "new": "Novo",
    "complete": "Completo",
    "exclusive": "Exclusivo",
    "simulpub": "Simulpub",
    "search_use_two_characters": "Use pelo menos 2 caracteres ao pesquisar por título.",
    "pref_hide_locked_chapters": "Ocultar capítulos bloqueados"
  }
};
