// Port of keiyoushi/extensions-source src/en/hm2d/HM2D.kt (generated by tools/generate.ts)
import { ChapterMode, Madara } from "../../../themes/madara/index.ts";

export default class HM2D extends Madara {
  override chapterMode = ChapterMode.MangaAjax;
}
