// Port of keiyoushi/extensions-source src/en/manga18free/Manga18Free.kt (generated by tools/generate.ts)
import { ChapterMode, Madara } from "../../../themes/madara/index.ts";

export default class Manga18Free extends Madara {
  override chapterMode = ChapterMode.AdminAjax;
}
