// Port of keiyoushi/extensions-source src/id/manhwalistorg/ManhwalistOrg.kt (generated by tools/generate.ts)
import { MangaThemesia } from "../../../themes/mangathemesia/index.ts";

export default class ManhwalistOrg extends MangaThemesia {}
