// Port of keiyoushi/extensions-source src/id/omicaso/Omicaso.kt (generated by tools/generate.ts)
import { MangaThemesia } from "../../../themes/mangathemesia/index.ts";

export default class Omicaso extends MangaThemesia {
  override mangaUrlDirectory = "/comik";
}
