// Port of keiyoushi/extensions-source src/en/sleepytranslations/SleepyTranslations.kt (generated by tools/generate.ts)
import { ChapterMode, Madara } from "../../../themes/madara/index.ts";

export default class SleepyTranslations extends Madara {
  override chapterMode = ChapterMode.MangaAjax;
}
