// Port of keiyoushi/extensions-source src/en/anisascans/AnisaScans.kt (generated by tools/generate.ts)
import { ClientBuilder } from "../../../sdk/index.ts";
import { ChapterMode, Madara } from "../../../themes/madara/index.ts";

export default class AnisaScans extends Madara {
  protected override configureClient(b: ClientBuilder) {
    b.rateLimit(3, 1000, (it: URL) => !it.pathname.startsWith("/wp-content/uploads/"));
    return b;
  }

  override chapterMode = ChapterMode.MangaAjax;
}
