// Port of keiyoushi/extensions-source src/en/aquamanga/AquaManga.kt (generated by tools/generate.ts)
import { MadaraNoAjax } from "../../../themes/madara/index.ts";

export default class AquaManga extends MadaraNoAjax {
  override supportsPostId = false;

  override archiveSelector() {
    return ".aqua-archive-card";
  }

  override archiveUrlSelector = ".aqua-archive-card__title a";

  override nextPageSelector() {
    return "a.next";
  }

  override mangaDetailsSelectorTitle = ".aqua-series-info__title";

  override mangaDetailsSelectorThumbnail = ".aqua-series-cover__img";

  override mangaDetailsSelectorDescription = ".aqua-series-synopsis";

  override mangaDetailsSelectorStatus = ".aqua-series-meta__status";

  override mangaDetailsSelectorGenre = ".aqua-series-genre-pill";

  override mangaDetailsSelectorAuthor = ".aqua-series-info__creator-value a";

  override mangaDetailsSelectorArtist = ".aqua-series-info__creator-value a";

  override chapterListSelector() {
    return ".aqua-ch-item";
  }

  override chapterUrlSelector = "a";

  override chapterNameSelector = ".aqua-ch-item__name";

  override chapterDateSelector = ".aqua-ch-item__time";
}
