// Port of keiyoushi/extensions-source src/en/ero18x/Ero18x.kt (generated by tools/generate.ts)
import { ChapterMode, MadaraNoAjax } from "../../../themes/madara/index.ts";

export default class Ero18x extends MadaraNoAjax {
  override chapterMode = ChapterMode.MangaAjax;
}
