// Port of keiyoushi/extensions-source src/en/gingertoon/GingeRTooN.kt (generated by tools/generate.ts)
import { DateTimeFormatter, Locale } from "../../../sdk/index.ts";
import { ChapterMode, MadaraNoAjax } from "../../../themes/madara/index.ts";

export default class GingeRTooN extends MadaraNoAjax {
  override chapterDateFormat = DateTimeFormatter.ofPattern("MM.dd.uuuu", Locale.ROOT);

  override chapterMode = ChapterMode.MangaAjax;
}
