// Port of keiyoushi/extensions-source src/en/cucumbermanga/CucumberManga.kt (generated by tools/generate.ts)
import { ChapterMode, Madara } from "../../../themes/madara/index.ts";

export default class CucumberManga extends Madara {
  override chapterMode = ChapterMode.MangaAjax;
}
