// Port of keiyoushi/extensions-source src/en/manhwa68/Manhwa68.kt (generated by tools/generate.ts)
import { DateTimeFormatter, Locale } from "../../../sdk/index.ts";
import { ChapterMode, Madara } from "../../../themes/madara/index.ts";

export default class Manhwa68 extends Madara {
  override chapterMode = ChapterMode.MangaAjax;

  override chapterDateFormat = DateTimeFormatter.ofPattern("MMM d, yyyy", Locale.US);

  override filterNonMangaItems = false;
}
