// Generated by tools/messages.ts from upstream wpcomics/assets/i18n. Do not edit.
import type { Messages } from "../../sdk/i18n.ts";

export const messages: Messages = {
  "en": {
    "STATUS": "Status",
    "STATUS_ALL": "All",
    "STATUS_ONGOING": "Ongoing",
    "STATUS_COMPLETED": "Completed",
    "GENRE": "Genre",
    "GENRES_RESET": "Tap 'Reset' to load genres",
    "OTHER_NAME": "Alternate Name"
  },
  "ja": {
    "STATUS": "状態",
    "STATUS_ALL": "全て",
    "STATUS_ONGOING": "連載中",
    "STATUS_COMPLETED": "完結済み",
    "GENRE": "ジャンル"
  },
  "vi": {
    "STATUS": "Trạng thái",
    "STATUS_ALL": "Tất cả",
    "STATUS_ONGOING": "Đang tiến hành",
    "STATUS_COMPLETED": "Hoàn thành",
    "GENRE": "Thể loại",
    "GENRES_RESET": "Ấn 'Reset' để tải danh sách thể loại",
    "OTHER_NAME": "Tên khác"
  }
};
