// Port of keiyoushi/extensions-source src/id/komikdewasaart/KomikDewasaArt.kt (generated by tools/generate.ts)
import { MangaThemesia } from "../../../themes/mangathemesia/index.ts";

export default class KomikDewasaArt extends MangaThemesia {
  override mangaUrlDirectory = "/komik";

  override datePattern = "dd/MM/yyyy";
}
