// Generated by tools/messages.ts from upstream honeytoon/assets/i18n. Do not edit.
import type { Messages } from "../../../sdk/i18n.ts";

export const messages: Messages = {
  "en": {
    "chapter_locked_warning": "The chapter is locked. Try logging in to WebView",
    "switch_adult_title": "Show content +18",
    "switch_adult_summary": "Only adult content will be loaded",
    "switch_adult_toast": "Restart app to apply new setting"
  },
  "pt-BR": {
    "chapter_locked_warning": "O capítulo está bloqueado. Tente fazer login no WebView",
    "switch_adult_title": "Exibir conteúdo +18",
    "switch_adult_summary": "Somente contéudo adulto será carregado",
    "switch_adult_toast": "Reinicie o aplicativo para aplicar a nova configuração"
  }
};
