// Generated by tools/messages.ts from upstream mmrcms/assets/i18n. Do not edit.
import type { Messages } from "../../sdk/i18n.ts";

export const messages: Messages = {
  "en": {
    "filter_warning": "Ignored if using text search",
    "filter_missing_warning": "Press 'Reset' to attempt to show filters",
    "category_filter_title": "Category",
    "status_filter_title": "Status",
    "type_filter_title": "Type",
    "year_filter_title": "Year of release",
    "author_filter_title": "Author",
    "tag_filter_title": "Tag",
    "title_begins_with_filter_title": "Title begins with",
    "sort_by_filter_title": "Sort by"
  },
  "es": {
    "filter_warning": "Ignorados si se realiza una búsqueda textual",
    "filter_missing_warning": "Presione 'Restablecer' para intentar mostrar los filtros",
    "category_filter_title": "Categoría",
    "status_filter_title": "Estado",
    "type_filter_title": "Tipo",
    "year_filter_title": "Año de lanzamiento",
    "author_filter_title": "Autor",
    "tag_filter_title": "Etiqueta",
    "title_begins_with_filter_title": "El título comienza con",
    "sort_by_filter_title": "Ordenar por"
  }
};
