// Port of keiyoushi/extensions-source src/en/manhwamanhua/ManhwaManhua.kt (generated by tools/generate.ts)
import { ChapterMode, Madara } from "../../../themes/madara/index.ts";

export default class ManhwaManhua extends Madara {
  override filterNonMangaItems = false;

  override chapterMode = ChapterMode.MangaAjax;
}
